"""Regenerate paper_draft.md. Prose lives here, numbers live in the run JSONs.

    python scripts/paper.py

Same reasoning as `scripts/weekend.py`: a hand-written draft in a repository that
several turns of one loop write to gets deleted or half-overwritten, and its
numbers drift from the JSONs the moment a run is repeated. Generating it makes
both impossible. `[not measured]` is emitted wherever no run has produced a
figure.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

NM = "`[not measured]`"


def rd(p, d=None):
    try:
        return json.loads(Path(p).read_text())
    except (OSError, json.JSONDecodeError):
        return d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="runs/seed1")
    ap.add_argument("--out", default="paper_draft.md")
    a = ap.parse_args()

    ev = rd(Path(a.run) / "test_eval.json")
    evx = (rd(Path(a.run) / "test_crossed_eval.json")
           or rd("runs/UNTRACED_t4_base_s0/test_crossed_eval.json"))
    # See scripts/report.py: runs/speed.json and its two successors timed a cold
    # solver against a warm operator, so their like-for-like readings (1.47x,
    # 6.57x, 119.12x) are withdrawn. Only the symmetric bench may fill this
    # clause; if it is absent the section says so rather than reaching for them.
    sp = rd("runs/speed_symmetric.json")
    sp_withdrawn = rd("runs/speed.json")
    sp_drift = rd("runs/solver_drift.json")
    ss = rd("runs/seed_spread.json", {})
    dsn_fx = rd("runs/design_Tfixed.json")
    dsn_fr = rd("runs/design_Tfree.json")
    degen = rd("runs/design_degeneracy.json")
    rcurve = rd("runs/random_curve.json")
    rtest = rd("runs/random_curve_test.json")
    dt_honest = {m: rd(f"runs/design_Tfree_dtinit_{m}.json") for m in ("random", "mid")}
    invb = rd("runs/inverse_baseline.json")
    ver = rd("runs/verify_solver.json", {})
    cf = rd("runs/confound.json", {})

    L = ["# A recipe-conditioned neural operator for plasma etch surface evolution, "
         "and what it is worth for inverse design", "",
         "*Working draft, generated by `scripts/paper.py`. Numbers are read from run "
         "JSONs; `RESULTS.md` is authoritative if the two disagree. Sections with no run "
         f"behind them read {NM}.*", "",
         "## Abstract", "",
         "We learn a recipe-conditioned Fourier neural operator for 2-D plasma-etch surface "
         "evolution against a ViennaPS ground truth, and measure it against a KPI with three "
         "clauses. The accuracy clause is met comfortably on the distribution the operator "
         "was trained for and missed by roughly an order of magnitude on a crossed split "
         "that removes an artefact of how the training timesteps were chosen. The speedup "
         "clause is unreachable at 1000× under every reading we can defend, and the "
         "measurement that decides it is the *denominator*, not the model. The value of the "
         "surrogate for inverse design is reported in the only currency that has meaning "
         "here — simulator calls saved.", "",
         "The contribution is less the operator than the protocol: three of the four "
         "numbers this project nearly reported were wrong in ways that a JSON artefact and "
         "a plausible protocol paragraph would not have caught.", "",
         "## 1. Problem", "",
         "Plasma etch takes a masked wafer and a recipe — ion flux, etchant flux, oxygen "
         "flux, ion energy — and evolves the exposed surface. The forward problem is a "
         "moving-boundary PDE solved by level-set advection with a flux field from a Monte "
         "Carlo transport calculation. The inverse problem, which is the one a process "
         "engineer has, runs the other way: given a target profile, find the recipe. Each "
         "forward evaluation is expensive, so derivative-free search costs hundreds of "
         "simulations, and a differentiable surrogate is the obvious response. Whether that "
         "response pays is an empirical question about simulator calls, not about whether a "
         "surrogate can be fitted.", "",
         "> **KPI:** 2D 표면진화 rel-L2 ≤0.05 · 시뮬 대비 ≥1000× 가속 · 역설계 형상오차 ≤5%", "",
         "## 2. What each clause is allowed to mean", "",
         "Each clause admits a loose reading and a strict one, and the loose reading is "
         "reachable by accident. These were fixed before any model was trained.", "",
         "**2.1 rel-L2 on a signed distance field is not one number.** Most of the window is "
         "far from the interface, where the SDF is a smooth ramp with a large norm and no "
         "information about the etch. We report whole-window and narrow-band values and take "
         "the band (|φ| < 1.5 µm of the *ground-truth* interface) as the headline; keying the "
         "band on the target rather than the prediction stops a model widening its own "
         "examination room. Three nulls accompany every accuracy number: **persistence** "
         "(predict no change), **recipe-blind** (advance by the train-set mean displacement, "
         "ignoring the recipe), and **uniform recession** (offset by the *ground truth's* mean "
         "displacement — an oracle that lacks only shape).", "",
         "**2.2 A speedup is a comparison between two machines unless you say otherwise.** We "
         "report a grid over device, thread count and batch size, in seconds per simulated "
         "wafer, and take the like-for-like cell — same device, same thread count — as the "
         "verdict. Solver wall-clock varies about 40× with machine load, so the benchmark "
         "re-times in a clean subprocess with threads pinned and records the load average.", "",
         "**2.3 Shape error needs a denominator, and a simulator.** Normalised area "
         "difference divided by *the area the target etch removed*; normalising by total "
         "solid area instead differs by about 5× on a hand-computable case. Areas are "
         "sub-cell, because hard thresholding quantises to a whole grid cell — ~3% of a "
         "typical removed area, the same order as the 5% being judged. The achieved profile "
         "comes from **re-running the proposed recipe in ViennaPS**, and the gap to the "
         "surrogate's own opinion is reported as the surrogate-reality gap.", "",
         "## 3. Method", ""]

    L += [f"**Ground truth.** ViennaPS 4.6.2 with ViennaLS **5.8.5** "
          "(`pip install viennaps` resolves ViennaLS to 5.9.0, which changes the registered "
          "`viennahrle::BoundaryType` and makes `import viennaps` fail outright), "
          "`SF6O2Etching` on a 2-D trench. State is an exact geometric SDF resampled on a "
          "fixed window from the explicit zero contour of the top level set — not the "
          "simulator's own level set, whose bounding box grows as the trench deepens so "
          "frames would not share a frame of reference.", ""]

    if ver.get("sdf_exactness"):
        gc = (ver.get("grid_convergence") or {}).get("pairs") or []
        iso = max(c["rel_err"] for c in ver["isotropic_recession"])
        L += ["Verified before any model existed: the rasteriser reproduces an analytic plane "
              f"to **{ver['sdf_exactness']['max_abs_err_um']:.1e} µm**, `IsotropicProcess` "
              f"recession matches rate × time to **{iso:.1e} relative**, and grid refinement "
              + (f"from Δ={gc[-1]['coarse_delta']} to Δ={gc[-1]['fine_delta']} moves the surface "
                 f"by **{gc[-1]['mean_sdf_shift_um']:.4f} µm mean**. " if gc else "")
              + "The dataset is generated at the coarser grid, so that is the accuracy floor: "
                "an operator error below it measures the discretisation, not the physics.", ""]

    L += ["**The timestep is part of the problem.** The etch rate spans ~20× across the "
          "recipe box, so a single global dt leaves most of the box nearly static — and a "
          "static target is one persistence solves for free. Each trajectory therefore gets "
          "its own dt from a cheap discarded probe, and dt is a conditioning input. This "
          "makes the operator's job harder (it must learn the rate law, not apply it) but it "
          "also compresses how much per-step displacement varies across recipes, which "
          "§5.1 quantifies and corrects for with a crossed split.", "",
          "**Operator.** `SpectralConv2d` and the FNO block are reused unchanged from "
          "`pde-neural-operator` (real-stored complex weights, so gradients stay real and DDP "
          "can compress the all-reduce to bf16; FFTs forced to fp32). The one substantive "
          "change is conditioning: a discrete PDE-family embedding is replaced by an MLP over "
          "the standardised recipe vector. The model predicts the **residual** "
          "φ(t+dt) − φ(t) — not only an optimisation convenience, since predicting φ directly "
          "would let the identity map look competent.", "",
          "**Inverse design.** Recipes are parameterised through a sigmoid into the training "
          "box, so the optimiser cannot leave the region the simulator was sampled in, and "
          "solutions pinned against a box wall are counted separately. Targets are final "
          "profiles of held-out trajectories, so a solution is known to exist. Four rows per "
          "target: `true_resim` (a determinism tripwire that must be ≈0), `operator_gd` "
          "scored in ViennaPS, `surrogate_opinion`, and a matched-budget random search.", "",
          "## 4. Results", ""]

    # ---- clause 1
    L += ["### 4.1 Clause 1 — surface-evolution accuracy", ""]
    if ev:
        k = ev["kpi_clause_rel_l2"]
        L += [f"Held-out test split, {ev['n_trajectories']} trajectories × {ev['steps']} "
              f"autoregressive steps, model `{a.run}`.", "",
              "| predictor | band rel-L2 | terminal step |", "|---|---|---|",
              f"| **operator** | **{k['value']:.4f}** | {k['value_terminal_step']:.4f} |",
              f"| persistence null | {k['persistence_null']:.4f} | — |",
              f"| recipe-blind null | {k['recipe_blind_null']:.4f} | — |",
              f"| uniform-recession null (oracle) | {k['uniform_recession_null']:.4f} | — |",
              f"| *loose full-window reading* | *{k['full_window_reading']:.4f}* | — |", "",
              f"**{'MET' if k['met'] else 'NOT MET'}** — {0.05/k['value']:.1f}× of headroom against "
              f"≤0.05, beating every null by two orders of magnitude. The full-window reading "
              f"is {k['value']/k['full_window_reading']:.0f}× more flattering than the band reading on "
              "identical predictions: the loose reading of this clause is not a weaker test, "
              "it is a different one.", ""]
        grp = [g for g in ss.get("groups", [])
               if not g["config"]["blind"] and g.get("n_seeds", 0) >= 2]
        if grp:
            g = grp[0]
            L += [f"Across converged seeds {g['seeds']}: "
                  f"{', '.join(f'{v:.4f}' for v in g['band_rel_l2'])}, range "
                  f"**{g['range']:.5f}** — two orders of magnitude below the threshold, so the "
                  "in-distribution verdict is not seed-sensitive.", ""]
        if evx:
            kx = evx["kpi_clause_rel_l2"]
            L += [f"**The qualification that must travel with the number.** On the crossed-dt "
                  f"split — same recipe box, timestep drawn *independently of the recipe* — the "
                  f"same architecture scores **{kx['value']:.4f}** (terminal "
                  f"{kx['value_terminal_step']:.4f}), a **miss**, and a factor of "
                  f"{kx['value']/k['value']:.1f} worse.", ""]
            splits = {s["split"]: s for s in cf.get("splits", []) if isinstance(s, dict)}
            if "test" in splits and "test_crossed" in splits:
                t = splits["test"]["per_trajectory_mean_displacement"]["max_over_min"]
                c = splits["test_crossed"]["per_trajectory_mean_displacement"]["max_over_min"]
                L += [f"Per-step displacement spans **{t:.1f}×** across recipes on the adaptive "
                      f"split against **{c:.1f}×** on the crossed one, so the protocol "
                      f"compressed the rate law's range by about {c/t:.1f}×. Clause 1 is met on "
                      "the distribution the operator was trained for and not on the one a user "
                      "would bring; both numbers are reported and neither replaces the other.", ""]
        abl = (ss.get("conditioning_ablation") or [None])[0]
        if abl:
            L += [f"**The conditioning is load-bearing.** An identical architecture trained "
                  f"with the recipe hidden scores {abl['blind_mean']:.4f} against "
                  f"{abl['conditioned_mean']:.4f} conditioned — a factor of "
                  f"**{abl['ratio']:.1f}**. Stronger than beating the recipe-blind *null*, "
                  "because the blind model may fit everything except the recipe.", ""]
    else:
        L += [NM, ""]

    # ---- clause 2
    L += ["### 4.2 Clause 2 — speedup", ""]
    if sp:
        S, ks = sp["solver"], sp["kpi_clause"]
        L += ["A speedup is a ratio, and both a numerator and a denominator can be "
              "chosen to flatter it. Two choices decide this one. First, **CPU-seconds "
              "rather than wall-seconds**: contention does not slow two processes with "
              "different threading behaviour by the same factor, so a wall-clock ratio "
              "measured on a shared box is not a property of the implementations. "
              "Second, **the one-time cost is paid on both sides or neither**: ViennaPS "
              f"charges a large initialisation inside its `apply()` "
              f"(cold/warm = {sp['solver']['cold_over_warm']:.2f}×) and the operator pays "
              "FFT-plan creation on its first call, so a cold reference timed against a "
              "warmed surrogate awards the clause the difference. Both readings are "
              "therefore reported for every horizon.", "",
              "| configuration | CPU-s / wafer | CPU/wall | vs solver, same reading |",
              "|---|---|---|---|"]
        for rd_ in ("marginal_warm", "cold_single_wafer"):
            L.append(f"| ViennaPS, 1 thread, {rd_} | {S[rd_]['median_cpu']:.4f} | "
                     f"{S[rd_]['cpu_over_wall_median']:.2f} | — |")
        for r, e in sp["arms"].items():
            for rd_ in ("marginal_warm", "cold_single_wafer"):
                L.append(f"| operator `{r.split('/')[-1]}`, "
                         f"{e['applications_per_wafer']} application(s)/wafer, {rd_} | "
                         f"{e[rd_]['median_cpu']:.4f} | "
                         f"{e[rd_]['cpu_over_wall_median']:.2f} | "
                         f"{e[rd_]['speedup_cpu']:.2f}× |")
        L += ["",
              f"The best of these {len(ks['all_rows'])} rows is "
              f"**{ks['best_value']:.2f}×** (`{ks['best_arm'].split('/')[-1]}`, "
              f"{ks['best_reading']}), short of 1000× by a factor of "
              f"**{ks['shortfall_factor']:.0f}**, so the clause is **UNREACHABLE** with "
              "the table as the evidence. The `CPU/wall` column is a check rather than a "
              "setting: a row labelled one thread whose ratio exceeded 1 would void the "
              "like-for-like claim resting on it.", "",
              "**At one step per application the operator is slower than the simulator "
              "it replaces.** That is the result the horizon sweep exists to explain: "
              "cost is linear in applications per wafer, and only by advancing ten "
              "dataset timesteps per application does the surrogate become faster at "
              "all. The accuracy cost of doing so is §4.1's, and it is not small.", ""]
        if sp_drift:
            L += ["**A denominator we cannot reproduce, reported as such.** Three earlier "
                  "measurements in this repository record the same fixed reference — "
                  "identical code, grid and step count — at 1.538, 8.457 and 8.390 "
                  "seconds per wafer. Under three separate conditions at comparable load "
                  f"the reference costs {sp_drift['verdict']['fresh_median_s_per_wafer']:.2f} s "
                  f"cold and {sp_drift['verdict']['reuse_median_s_per_wafer']:.3f} s warm. "
                  "Neither box load (1.15× across a 3.6× load range) nor process reuse "
                  "(which lowers the figure) accounts for the discrepancy. We have no "
                  "explanation for it, so the three like-for-like speedups derived from "
                  "those files — 1.47×, 6.57× and 119.12× — are withdrawn rather than "
                  "reinterpreted, and this section quotes none of them.", ""]
    else:
        L += ["`[not measured]` — `runs/speed_symmetric.json` is absent. The earlier "
              "speed files in this repository timed a cold reference against a warmed "
              "surrogate and their like-for-like readings are withdrawn, so this section "
              "reports nothing rather than quoting them.", ""]
    if sp:
        L += [
              "The operator's advantage is not that it does less arithmetic — on one CPU "
              "core, one step per application, it is *slower* than the simulator — but "
              "that its arithmetic is dense, regular and batchable. The solver's is a "
              "scattered Monte Carlo ray trace, which is also why it refuses to "
              "parallelise. That is the honest statement of what a learned operator buys "
              "on this problem, and it is a statement about hardware utilisation rather "
              "than about operation count.", ""]
    else:
        L += [NM, ""]

    # ---- clause 3
    L += ["### 4.3 Clause 3 — inverse-design shape error", ""]
    for tag, dsn in [("total etch time pinned to the target (a constraint, and "
                      "measured worse than searching it)", dsn_fx),
                     ("total etch time searched", dsn_fr)]:
        L += [f"**Protocol: {tag}.**", ""]
        if dsn:
            s = dsn["summary"]
            kd = s["kpi_clause_shape_error"]
            rows = ["| method | area error (mean) | median | p90 | max |", "|---|---|---|---|---|"]
            names = {"true_resim": "true recipe re-simulated (tripwire)",
                     "operator_gd": "**gradient design, scored in ViennaPS**",
                     "surrogate_opinion": "gradient design, surrogate's own opinion",
                     "random_search": "random search over the operator (see 4.3.1 for its budget)"}
            for kk, nm in names.items():
                if kk in s["area_error_vs_removed"]:
                    ae = s["area_error_vs_removed"][kk]
                    rows.append(f"| {nm} | {ae['mean']:.4f} | {ae['median']:.4f} | "
                                f"{ae['p90']:.4f} | {ae['max']:.4f} |")
            L += rows + ["",
                  f"**{'MET' if kd['met'] else 'NOT MET'}** at ≤0.05 on the mean. "
                  f"{kd.get('frac_targets_under_5pct', float('nan'))*100:.0f}% of targets "
                  f"individually under 5%, p90 {kd.get('p90', float('nan')):.4f}. "
                  f"Surrogate-reality gap {kd.get('surrogate_reality_gap', float('nan')):+.4f}. "
                  f"Determinism tripwire (true recipe re-simulated) max "
                  f"{kd.get('simulator_determinism_check', float('nan')):.2e}.", ""]
        else:
            L += [NM, ""]

    # ---- 4.3.1 the baseline's budget
    L += ["#### 4.3.1 The baseline, as a curve rather than a point", ""]
    if rcurve:
        c, comp, v = rcurve["curve"], rcurve["compute"], rcurve["verdict"]
        gdm = rcurve["gd_reference"]["mean_area_error"]
        L += [f"Gradient descent used {comp['gd_restarts']} restarts × "
              f"{comp['gd_iters']} iterations, i.e. {comp['gd_rollouts_forward']} rollouts "
              f"forward and as many backward — about {comp['gd_forward_equivalents']} "
              "forward-equivalents. The random-search row above used 256 candidates. Those "
              "budgets are not comparable, so the baseline is reported as a curve. Nested "
              "prefixes of one candidate stream per target, so the ranking is free of "
              "independent-draw noise; random search keeps the target's true etch time "
              "throughout, which makes it stronger than the method it is compared against.",
              "",
              "| candidates | area error (mean) | median | max |", "|---|---|---|---|"]
        L += [f"| {b} | {c[b]['mean']:.4f} | {c[b]['median']:.4f} | {c[b]['max']:.4f} |"
              for b in sorted(c, key=int)]
        L += ["", f"Gradient descent on the same targets: **{gdm:.4f}**.", ""]
        if v["h3_falsified"]:
            L += [f"Random search reaches gradient descent's error at "
                  f"{min(v['budgets_reaching_gd'])} candidates, so **H3 is falsified**: the "
                  "advantage was in part a budget. What the operator demonstrably provides is "
                  "a cheap and accurate *ranker*; the claim that its gradients are what "
                  "produce the answer is not supported by this comparison, and the honest "
                  "statement of the contribution is the differentiable surrogate as a search "
                  "oracle, at whatever budget the user can afford.", ""]
        else:
            L += ["No budget's *mean* reaches gradient descent's. A few per cent over 20 "
                  "targets is not a result on its own, so the comparison is settled by a "
                  "paired test rather than by the means.", ""]
    if rtest:
        bt, tv = rtest["budgets"], rtest["verdict"]
        L += ["Each budget is evaluated on the same 20 targets with the same model, so the "
              "target is the unit of analysis. We report an exact sign-flip permutation test "
              "over all 2^20 sign assignments of the per-target differences, and an exact "
              "binomial sign test.", "",
              "| candidates | budget vs GD | mean paired diff (random - GD) | GD wins | "
              "p (sign-flip) | p (sign test) |", "|---|---|---|---|---|---|"]
        L += [f"| {b} | {bt[b]['budget_ratio_vs_gd']:.1f}x | {bt[b]['mean_paired_diff']:+.4f} "
              f"| {bt[b]['gd_wins']}/{bt[b]['n_targets']} | {bt[b]['p_signflip_exact']:.4f} "
              f"| {bt[b]['p_sign_test_exact']:.4f} |" for b in sorted(bt, key=int)]
        nb = tv["smallest_budget_indistinguishable"]
        if nb is not None:
            L += ["", f"Gradient descent is significantly better at every budget up to "
                  f"{max(tv['budgets_where_gd_wins_significantly'], key=int)} candidates and "
                  f"is not separable from random search at {nb} "
                  f"({bt[nb]['budget_ratio_vs_gd']:.1f}x its forward-equivalent budget; "
                  f"{bt[nb]['gd_wins']}/{bt[nb]['n_targets']} targets, p = "
                  f"{bt[nb]['p_signflip_exact']:.3f}). **The contribution is therefore a "
                  f"compute ratio — about {bt[nb]['budget_ratio_vs_gd']:.0f}x less search for "
                  f"the same profile error — and not a better optimum.** We note the likely "
                  f"reason and its limit: the recipe space here is four-dimensional with a "
                  f"smooth forward map, where 16k samples are dense. The prediction that "
                  f"follows is that the gradient advantage grows with recipe dimension; we "
                  f"have not tested it, and it is the experiment that would decide how far "
                  f"this result generalises.", ""]
        else:
            L += ["", "Gradient descent separates from random search at every budget tested.",
                  ""]
    else:
        L += [NM, ""]

    # ---- 4.3.2 the warm start
    L += ["#### 4.3.2 Whether the searched-duration arm was warm-started", ""]
    if dsn_fr:
        g0 = dsn_fr["targets"][0]["operator_gd_surrogate"]
        L += ["The published searched-duration arm initialised its duration parameter at the "
              "target's own dt, which `gen_data` had obtained by probing the true recipe's "
              "etch rate. The arm was labelled honest and was warm-started at the answer; an "
              "adversarial review found it. The optimiser does leave that start — the "
              "recovered duration is "
              f"{sum(abs(r['operator_gd_surrogate']['dt_rel_err']) for r in dsn_fr['targets'])/len(dsn_fr['targets']):.1%} "
              "from the true value on average — but that is an argument, not a measurement.",
              ""]
        if any(dt_honest.values()):
            L += ["| duration initialisation | area error (mean) | max | targets < 5% |",
                  "|---|---|---|---|"]
            L += [f"| target's own dt (published, warm-started) | "
                  f"{dsn_fr['summary']['area_error_vs_removed']['operator_gd']['mean']:.4f} | "
                  f"{dsn_fr['summary']['area_error_vs_removed']['operator_gd']['max']:.4f} | "
                  f"{dsn_fr['summary']['kpi_clause_shape_error']['frac_targets_under_5pct']:.0%} |"]
            for m, d in dt_honest.items():
                if d:
                    a_ = d["summary"]["area_error_vs_removed"]["operator_gd"]
                    L += [f"| {m}, independent of the target | {a_['mean']:.4f} | "
                          f"{a_['max']:.4f} | "
                          f"{d['summary']['kpi_clause_shape_error']['frac_targets_under_5pct']:.0%} |"]
            L += [""]
        else:
            L += ["Independent initialisations: `[not measured]` — queued, and this section "
                  "fills from `runs/design_Tfree_dtinit_*.json` when they land. Until then "
                  "the searched-duration number should be read as warm-started.", ""]
    else:
        L += [NM, ""]

    # ---- 4.3.3 what shape error does not certify
    L += ["#### 4.3.3 What a matched profile does not certify", ""]
    if degen:
        L += ["Shape error is the clause. Recipe recovery is a different quantity and it is "
              "not met, which matters because the two are easy to conflate when selling a "
              "process twin.", "",
              "| protocol | shape error | recipe distance (RMS, fraction of box) | beyond 10% "
              "of box | duration rel. error | corr with shape error |",
              "|---|---|---|---|---|---|"]
        for arm in degen["arms"]:
            rd_ = arm["recipe_distance_unit_box"]
            L += [f"| {'T searched' if arm['dt_optimised'] else 'T pinned'} | "
                  f"{arm['shape_error_area_vs_removed']['mean']:.4f} | "
                  f"{rd_['rms']['mean']:.3f} | "
                  f"{rd_['frac_beyond_10pct_of_box']:.0%} | "
                  f"{arm['etch_time_rel_error']['mean']:.3f} | "
                  f"{arm['corr_recipe_distance_vs_shape_error']:.3f} |"]
        L += ["", "The forward map is degenerate over (rate × time): distinct processes reach "
              "the same profile, so matching a profile does not identify the process that "
              "produced it. The weak correlation is the mechanical form of that statement — a "
              "small shape error carries almost no information about whether the recipe is "
              "right. The deliverable is profile targeting, not recipe identification, and "
              "breaking the degeneracy would need extra observables (depth and sidewall angle "
              "and duration) rather than a better optimiser.", ""]
    else:
        L += [NM, ""]

    L += ["### 4.4 What the surrogate is worth, in simulator calls", ""]
    if invb:
        L += [f"Gradient design spends **0** simulator calls searching and 1 verifying. Random "
              f"search over the same box, every candidate evaluated in ViennaPS, on the same "
              f"{invb['n_targets']} targets with a budget of {invb['budget']}: mean final area "
              f"error {invb['random_search_final_mean']:.4f} against "
              f"{invb['gradient_mean']:.4f} for gradient design. Median calls needed to match "
              f"the gradient answer: {invb['calls_to_match_gradient']['median_when_matched']}; "
              f"{invb['calls_to_match_gradient']['n_never_matched']} targets never matched "
              "within budget.", ""]
    else:
        L += [NM, ""]

    L += ["## 5. Threats to validity", "",
          "- **Single process chemistry.** Everything is `SF6O2Etching` on a trench. No claim "
          "is made about another chemistry or a hole geometry.",
          "- **The band width is a choice.** 1.5 µm is about ten grid cells; sensitivity to it "
          f"is {NM}.",
          "- **Inverse-design targets are in-distribution by construction**, which isolates "
          "the optimiser's failure from the surrogate's extrapolation but makes the reported "
          "shape error a lower bound on what a novel target would cost. Concretely: each "
          "target is a profile the simulator produced from a recipe inside the training box, "
          "with the true initial geometry supplied, at a depth the generator chose. Nothing "
          "here measures inversion of an independently specified manufacturing target, a "
          "different depth regime, or a geometry outside the box.",
          "- **Shape error is a global area difference.** A local defect — a notch, a "
          "sidewall deviation, a critical-dimension error — contributes to it only in "
          "proportion to its area, and a larger removed area flatters the same absolute "
          "defect. The bound that answers this is the worst-case Hausdorff distance, which is "
          "reported beside the area figure and, on the searched-duration arm, is a fraction "
          "of one grid cell. Hausdorff is not what the clause is scored on, so it qualifies "
          "the verdict rather than constituting it.",
          "- **The occupancy metric is a smoothed area fraction**, exact only for contours "
          "parallel to a cell edge, and two distinct sub-cell geometries can share a cell "
          "fraction. The hard sign-threshold reading is reported alongside it and the two "
          "differ by about a thousandth, which bounds the effect without removing it.",
          "- **The crossed split drops trajectories that leave the window**, so it is biased "
          "against fast recipes at long dt and its error is if anything optimistic.",
          "- **Seeds.** Comparisons are screens until run at 8 seeds per arm with an exact "
          "test. The converged-seed range is reported wherever a comparison is made.",
          "- **Accuracy is already below the ground truth's own grid error**, so further "
          "in-distribution gains fit the Δ=0.2 discretisation rather than the physics.", "",
          "## 6. What would change the verdict", "",
          "- **Clause 2** needs a cheaper operator, not a better one: roughly 3× cheaper at "
          "equal accuracy would bring the batched figure to 1000×. Since accuracy is already "
          "below the solver's grid error there is headroom to spend, and a deliberately "
          "undersized operator is the cheapest outstanding experiment.",
          "- **Clause 1's crossed-split miss** would be addressed by training on a mixture of "
          "adaptive and independent timesteps. That changes the protocol, so before/after "
          "numbers would not be comparable and both would have to be reported.", ""]

    L += ["## 7. Future work, as left at the declaration", "",
          "The project was declared UNREACHABLE with clause 2 short by ~680x. These are the "
          "questions that were open at that point, written down rather than pursued, because "
          "a further reading of an already-decided clause is not progress.", "",
          "1. **Does the gradient advantage grow with recipe dimension?** Section 4.3.1 finds "
          "gradient descent and random search indistinguishable at 9x budget on a 4-D recipe "
          "box. The obvious explanation is that the box is small and smooth. The experiment: "
          "the same comparison on a recipe parameterisation of 8, 16 and 32 dimensions "
          "(spatially varying flux, or a time-varying recipe schedule), at matched "
          "forward-equivalents, with the same paired exact test. If the gap does not widen, "
          "the differentiable surrogate is a ranker and should be sold as one.",
          "2. **Does clause 3 survive an independently specified target?** Every target here "
          "is a profile ViennaPS produced from a recipe inside the training box, so a "
          "solution provably exists. A target drawn from a device specification instead — a "
          "required depth, sidewall angle and bow — would test inversion rather than "
          "round-tripping. It needs a target generator that is not the simulator, which is "
          "why it was not attempted.",
          "3. **Is the (rate x time) degeneracy breakable with more observables?** Section "
          "4.3.3 shows a matched profile does not identify the recipe. Adding an endpoint "
          "trace or an intermediate profile as a second observable is the standard fix and is "
          "cheap to generate; whether it identifies the recipe is a measurement nobody here "
          "has taken.",
          "4. **A deliberately undersized operator for clause 2.** Accuracy sits below the "
          "solver's own grid error, so there is headroom to trade. This is the only route to "
          "the speedup clause that does not change the hardware comparison, and even a 3x "
          "cheaper operator at equal accuracy leaves the like-for-like figure far short — "
          "which is why the clause was declared unreachable rather than left open.", ""]

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
