"""Regenerate the paper draft's status block from the run JSONs.

    python scripts/paper_status.py            # rewrite the block in place
    python scripts/paper_status.py --check    # exit 1 if the block is stale

**Why this exists.** `RESULTS.md` and `WEEKEND.md` are generated from run JSONs
by scripts, and `paper_draft.md` is not -- so it is the one document in this
repo that can go quietly stale, and it did. On 2026-09-11 its abstract still
read "the speedup clause is unreachable at 1000x under every reading we can
defend" and its 4.2 headline was **9.58x, UNREACHABLE by a factor of 104**,
while `runs/clock_matched_speedup.json` was measuring a median of 1225-1265x
across four readings with 6-8 of 8 repeats over the threshold.

Nothing in the draft was fabricated -- every figure in it came from a run. The
failure is subtler and is the one this script addresses: **the numbers were
true of the architecture and denominator current when they were written, and
the document had no way to notice when they stopped being the repo's best
measurement.** 4.2's table prices the FNO family against the fixed-duration
denominator this repo has since retired; the specprop family and the
workload-matched denominator arrived later and only some sections were updated
by hand.

So the prose stays hand-written -- it is a paper, not a report -- and every
NUMBER in the status block is read from a JSON here. `--check` makes staleness
a test failure rather than something found by rereading the draft, which is how
it survived several turns.

**This block does not silently replace the draft's older numbers.** It is
inserted near the top with its own date and provenance, and the superseded
sections keep their figures, because a reader needs to see that the estimate
moved and by how much.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DRAFT = ROOT / "paper_draft.md"
BEGIN = "<!-- BEGIN GENERATED paper_status -- do not edit by hand -->"
END = "<!-- END GENERATED paper_status -->"


def read(p):
    p = Path(p)
    if not p.is_absolute():
        p = ROOT / p
    try:
        return json.loads(p.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def sources():
    """Every JSON this block reads, so --check knows what makes it stale."""
    return [ROOT / "runs" / n for n in (
        "clock_matched_speedup.json", "rank_cost.json",
        "specprop_profile.json", "bandwidth_bound.json",
        "design_Tfree_dtinit_mid.json",
    )] + sorted((ROOT / "runs").glob("cost_repro_*.json"))


def specprop_family():
    """Terminal-step rel-L2 per config, from the scored arms themselves."""
    import re
    agg = {}
    for d in sorted((ROOT / "runs" / "specprop").glob("*/")):
        te, ar = d / "test_eval.json", d / "args.json"
        if not (te.exists() and ar.exists()):
            continue
        m = re.match(r"(m\d+_ma\d+(?:_sm\d+)?(?:_r\d+)?)_s(\d+)$", d.name)
        if not m:
            continue
        a, t = read(ar), read(te)
        if not a or not t:
            continue
        e = agg.setdefault(m.group(1), {"params": a["params"], "v": []})
        e["v"].append(t["kpi_clause_rel_l2"]["value_terminal_step"])
    return agg


def build():
    L = [BEGIN, ""]
    L += ["> ## Status at regeneration",
          ">",
          "> *Generated by `scripts/paper_status.py` from the run JSONs. The "
          "prose below this block is hand-written and parts of it predate "
          "these measurements; where a section's figures have been superseded "
          "they are kept in place rather than edited away, so the reader can "
          "see what moved. `scripts/paper_status.py --check` fails when this "
          "block is older than the runs it reads.*", ">"]

    # ---- clause 1 -----------------------------------------------------
    fam = specprop_family()
    if fam:
        best = min(fam.items(), key=lambda kv: float(np.mean(kv[1]["v"])))
        cfg, e = best
        v = np.array(e["v"])
        L += [f"> **Clause 1 (rel-L2 <= 0.05).** Best in the `specprop` family "
              f"now measured: **`{cfg}` at {v.mean():.5f}** terminal-step "
              f"rel-L2 over {len(v)} seed(s) (range {v.max() - v.min():.5f}, "
              f"{e['params']:,d} parameters) — **NOT MET**, short by "
              f"{v.mean() / 0.05:.2f}x. {len(fam)} configurations scored and "
              f"none meets the clause.", ">"]

    # ---- clause 2 -----------------------------------------------------
    cm = read("runs/clock_matched_speedup.json")
    if cm:
        S, V = cm["summary"], cm.get("verdicts", {})
        L += ["> **Clause 2 (>= 1000x).** Four readings, "
              f"{cm['protocol']['repeats']} repeats, both sides' CPU clocks "
              "measured in the same invocation:", ">",
              "> | reading | median | range | meets 1000x | verdict |",
              "> |---|---|---|---|---|"]
        labels = {
            "speedup_raw_burst": "raw, burst (the published protocol)",
            "speedup_raw_sustained": "raw, sustained (duration-matched)",
            "speedup_cycle_matched_burst": "cycle-matched, burst",
            "speedup_cycle_matched_sustained": "cycle-matched, sustained",
        }
        for k, lab in labels.items():
            s = S.get(k)
            if not s:
                continue
            L += [f"> | {lab} | **{s['median']:.1f}x** | "
                  f"{s['min']:.0f}–{s['max']:.0f} | "
                  f"{s['n_meeting_target']}/{s['n']} | {V.get(k, '—')} |"]
        sg, ob = S.get("solver_ghz"), S.get("operator_burst_ghz")
        if sg and ob:
            L += [">",
                  f"> The two sides are not measured at the same clock: solver "
                  f"{sg['median']:.2f} GHz ({sg['min']:.2f}–{sg['max']:.2f}), "
                  f"operator {ob['median']:.2f} GHz "
                  f"({ob['min']:.2f}–{ob['max']:.2f}). A `powersave` governor "
                  f"treats a ~0.5 s solve and a ~0.35 ms burst differently, so "
                  f"the ratio carries a clock term belonging to neither "
                  f"implementation."]
        reps = [(p.name, read(p)) for p in sorted((ROOT / "runs")
                                                  .glob("cost_repro_*.json"))
                if "WRONG_DENOMINATOR" not in p.name]
        reps = [(n, d) for n, d in reps if d]
        if reps:
            L += [">",
                  "> The same architecture, priced under different box "
                  "conditions, meets the clause at very different rates — the "
                  "architecture is not what differs between these:", ">",
                  "> | run | loadavg | meets 1000x |", "> |---|---|---|"]
            for n, d in reps:
                sm = d["summary"]
                lr = sm.get("loadavg_range", [float("nan")] * 2)
                L += [f"> | `{n}` | {lr[0]:.0f}–{lr[1]:.0f} | "
                      f"{sm['n_invocations_meeting_target']}/"
                      f"{len(d['invocations'])} |"]
        L += [">"]

    # ---- where the cost is, and the bound on the margin route ---------
    pf, rc = read("runs/specprop_profile.json"), read("runs/rank_cost.json")
    if pf:
        st = pf["stages"]
        top = max((k for k in st if not k.startswith(("98", "99"))),
                  key=lambda k: st[k]["median_us"])
        L += [f"> **Where the cost is.** `{top}` is "
              f"**{st[top]['median_us']:.1f} us, "
              f"{st[top]['pct_of_forward']:.1f}%** of the forward — one "
              f"`nn.Linear` holding 98.0% of the parameters. Every FFT "
              f"together is "
              f"{sum(st[k]['pct_of_forward'] for k in ('01_rfft2', '07_irfft2') if k in st):.1f}%. "
              f"Fifteen turns of cost work in this repo targeted the "
              f"transforms.", ">"]
    if rc:
        b = rc.get("bound_on_this_route", {})
        rows = {r["a_rank"]: r for r in rc["rows"]}
        if b and 4 in rows:
            L += [f"> **The margin route, priced and bounded.** Factorising "
                  f"that layer buys **{rows[4]['speedup_vs_dense']:.2f}x** on "
                  f"the whole forward at rank 4, and the route is capped at "
                  f"**{b['best_possible_speedup']:.2f}x** even at rank 1, "
                  f"because a measured floor in the stage does not shrink with "
                  f"the rank. **No accuracy is measured for any rank yet.**",
                  ">"]

    # ---- clause 3 -----------------------------------------------------
    dz = read("runs/design_Tfree_dtinit_mid.json")
    if dz:
        k = dz["summary"]["kpi_clause_shape_error"]
        L += [f"> **Clause 3 (shape error <= 5%).** **{k['value']:.4f}** mean, "
              f"p90 {k['p90']:.4f}, max {k['max']:.4f}, "
              f"{k['frac_targets_under_5pct'] * 100:.0f}% of targets under 5% "
              f"— **{'MET' if k['met'] else 'NOT MET'}**, verified in the "
              f"simulator.", ">"]

    L += ["> **Superseded in the prose below.** §4.2's headline table prices "
          "the FNO family against the fixed-duration denominator this repo "
          "retired in §4.2.1, and reports 9.58x. That number is a real "
          "measurement of a different architecture against a different "
          "denominator; it is not this repo's current clause-2 estimate and "
          "the abstract's \"unreachable at 1000x under every reading we can "
          "defend\" no longer describes the table above.", ""]
    L += [END]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the block is missing or out of date")
    a = ap.parse_args()

    text = DRAFT.read_text()
    block = build()

    if BEGIN in text and END in text:
        i, j = text.index(BEGIN), text.index(END) + len(END)
        new = text[:i] + block + text[j:]
    else:
        # Insert after the abstract heading's paragraph block, before §1.
        marker = "\n## 1. Problem"
        if marker not in text:
            raise SystemExit("cannot locate '## 1. Problem' to insert before")
        i = text.index(marker)
        new = text[:i] + "\n" + block + "\n" + text[i:]

    if a.check:
        if new != text:
            print("STALE: paper_draft.md's status block does not match the "
                  "run JSONs. Run scripts/paper_status.py.", file=sys.stderr)
            return 1
        # Content equality is the whole check. An earlier version also
        # compared mtimes against the source JSONs, which is a false-positive
        # generator: a run rewriting a JSON without changing any derived
        # number would fail the suite while nothing was actually stale, and a
        # test that cries wolf during every sweep gets ignored.
        print("paper_draft.md status block is current")
        return 0

    DRAFT.write_text(new)
    print(f"wrote {DRAFT.name} status block "
          f"({len(block.splitlines())} lines) from "
          f"{sum(1 for p in sources() if p.exists())} run JSONs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
