"""Regenerate RESULTS.md from the run JSONs.

    python scripts/report.py

This is the only path by which a number enters a document in this repo. If a
figure is not in one of these JSONs it does not appear, and if a JSON is missing
the row says `[not measured]` rather than being quietly dropped -- a blank beats
a guess.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

NM = "[not measured]"


def read(p, default=None):
    p = Path(p)
    return json.loads(p.read_text()) if p.exists() else default


def cell(x):
    return str(x).replace("|", "\\|")


def table(rows, header):
    out = ["| " + " | ".join(cell(h) for h in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(cell(c) for c in r) + " |")
    return "\n".join(out)


def f(x, n=4):
    return NM if x is None else f"{x:.{n}f}"


def g(x, n=1):
    return NM if x is None else f"{x:,.{n}f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="runs/base")
    ap.add_argument("--data", default="data")
    ap.add_argument("--out", default="RESULTS.md")
    a = ap.parse_args()

    run = Path(a.run)
    verify = read("runs/verify_solver.json")
    gen = read(Path(a.data) / "gen_report.json")
    cfg = read(run / "args.json", {})
    ev = read(run / "test_eval.json")
    speed = read("runs/speed.json")
    design = read(run / "design.json")
    workers = read("runs/worker_scaling.json")
    invb = read("runs/inverse_baseline.json")

    L = ["# RESULTS — E4, etch-operator-twin", "",
         "Regenerated by `scripts/report.py` from run JSONs. Nothing here is typed by hand.",
         "", "> **KPI:** 2D 표면진화 rel-L2 ≤0.05 · 시뮬 대비 ≥1000× 가속 · 역설계 형상오차 ≤5%", ""]

    # ---- KPI scoreboard
    L += ["## KPI scoreboard", ""]
    rl = ev.get("kpi_clause_rel_l2") if ev else None
    sp = speed.get("kpi_clause") if speed else None
    sh = design["summary"].get("kpi_clause_shape_error") if design else None
    rows = [
        ["rel-L2 ≤ 0.05",
         f(rl["value"]) if rl else NM,
         ("MET" if rl["met"] else "NOT MET") if rl else NM,
         "rollout band rel-L2, test split" if rl else "—"],
        # Keyed on the like-for-like number. Keying it on the best cell of the
        # grid would award the clause to a batched H100 measured against a
        # single-threaded C++ solver.
        ["speedup ≥ 1000×",
         (g(sp["value"]) + "×") if sp else NM,
         ("MET" if sp and sp["value"] >= 1000 else "NOT MET") if sp else NM,
         (f"{sp['basis']}; throughput-vs-throughput "
          f"{g(sp.get('context_throughput_speedup'))}×, "
          f"largest cell in grid {g(sp.get('context_naive_best_cell'))}× "
          f"(`{sp.get('context_naive_configuration')}`, different hardware)") if sp else "—"],
        ["shape error ≤ 5%",
         (f(sh["value"] * 100, 2) + "%") if sh else NM,
         ("MET" if sh["met"] else "NOT MET") if sh else NM,
         "normalised area error, measured in ViennaPS" if sh else "—"],
    ]
    L += [table(rows, ["clause", "measured", "verdict", "protocol"]), ""]

    # ---- ground truth
    L += ["## Ground truth verification", ""]
    if verify:
        L += [f"ViennaPS {verify['viennaps']} / ViennaLS {verify['viennals']}, 1 OpenMP thread.", ""]
        rows = [["SDF rasteriser vs analytic plane",
                 f"{verify['sdf_exactness']['max_abs_err_um']:.2e} µm (max)",
                 f"< {verify['pass']['sdf_tol_um']} µm",
                 "PASS" if verify["pass"]["sdf_exactness"] else "FAIL"]]
        for c in verify["isotropic_recession"]:
            rows.append([f"isotropic recession, t={c['duration_min']} min",
                         f"{c['rel_err']:.2e} (rel)",
                         f"< {verify['pass']['isotropic_rel_tol']}",
                         "PASS" if c["rel_err"] < verify["pass"]["isotropic_rel_tol"] else "FAIL"])
        L += [table(rows, ["check", "measured", "tolerance", "verdict"]), ""]
        rows = [[f"Δ {p['coarse_delta']} → {p['fine_delta']}",
                 f"{p['mean_sdf_shift_um']:.4f} µm", f"{p['max_sdf_shift_um']:.4f} µm"]
                for p in verify["grid_convergence"]["pairs"]]
        L += ["**Grid convergence.** The dataset is generated at Δ = "
              f"{gen['grid_delta'] if gen else '?'}, so its own discretisation error sets a floor "
              "below which an operator error is measuring the solver's grid, not the operator.", ""]
        L += [table(rows, ["refinement", "mean surface shift (band)", "max"]), ""]
    else:
        L += [NM, ""]

    # ---- dataset
    L += ["## Dataset", ""]
    if gen:
        # .get, not [], throughout: a report that dies on one absent field tells
        # you nothing about the fields that *are* there, which defeats the point
        # of emitting [not measured] per cell.
        rows = [[s.get("split", NM), s.get("kept", NM), s.get("rejected_out_of_window", NM),
                 (f"{s['generate_wall_s']:.0f}" if "generate_wall_s" in s else NM),
                 s.get("workers", NM)] for s in gen["splits"]]
        L += [table(rows, ["split", "trajectories", "rejected (left window)",
                           "generation wall (s)", "workers"]), ""]
        L += [f"{gen['steps']} timesteps per trajectory on a {gen['grid_n']}×{gen['grid_n']} window "
              f"x ∈ {gen['window']['x']} µm, y ∈ {gen['window']['y']} µm. "
              "Timestep is chosen per recipe so every trajectory covers a comparable etch depth "
              f"({gen['target_depth_range'][0]}–{gen['target_depth_range'][1]} µm); dt is a model input.", ""]
        L += ["Recipe box (the region inverse design is confined to):", ""]
        L += [table([[k, v[0], v[1], v[2]] for k, v in
                     {**gen["recipe_box"], **gen["geom_box"]}.items()],
                    ["knob", "low", "high", "sampling"]), ""]
    else:
        L += [NM, ""]

    # ---- accuracy
    L += ["## Clause 1 — surface-evolution accuracy", ""]
    if ev:
        L += [f"Test split, {ev['n_trajectories']} trajectories × {ev['steps']} steps. "
              f"Band = |φ| < {ev['band_um']} µm around the ground-truth interface.", "",
              "Every row carries three nulls, and a number that does not beat all three is "
              "not a result.", "",
              "- **Persistence** — predict no change. An SDF over one step is mostly "
              "unchanged, so this scores far better than it deserves to.",
              "- **Recipe-blind** — advance every surface by the train-set mean per-step "
              "displacement, ignoring recipe, dt and target. This is the null that matters "
              "here: because the timestep is chosen per recipe so every trajectory covers a "
              "comparable depth, per-step displacement is nearly recipe-independent *by "
              "construction*, and a model could score well while ignoring the recipe "
              "entirely. Beating this is the evidence that the conditioning carries shape "
              "information.",
              "- **Uniform recession** — offset by the *ground truth's* mean displacement. "
              "This is an oracle: it is handed the correct amount of etch and lacks only the "
              "shape. Losing to it is not fatal; beating it is strong.", ""]
        rows = []
        for label, blk in [("one step (teacher forced)", ev["one_step"]),
                           ("full rollout", ev["rollout"])]:
            for k, name in [("op", "**operator**"), ("persist", "persistence null"),
                            ("blind", "recipe-blind null"),
                            ("uniform", "uniform-recession null (oracle)")]:
                if k not in blk:
                    continue
                rows.append([label, name, f(blk[k]["band"]["mean"]),
                             f(blk[k]["band"]["median"]), f(blk[k]["band"]["p90"]),
                             f(blk[k]["full"]["mean"])])
        L += [table(rows, ["protocol", "predictor", "band rel-L2 (mean)", "median", "p90",
                           "full-window rel-L2 (mean)"]), ""]
        L += ["Rollout band rel-L2 by step (drift compounding):", "",
              "| step | " + " | ".join(str(i + 1) for i in range(len(ev["rollout_band_rel_l2_by_step"]))) + " |",
              "|---|" + "---|" * len(ev["rollout_band_rel_l2_by_step"]),
              "| band rel-L2 | " + " | ".join(f"{v:.4f}" for v in ev["rollout_band_rel_l2_by_step"]) + " |", ""]
        gm = ev["final_profile_geometry"]
        L += ["Geometry of the final predicted profile:", "",
              table([["normalised area error", f(gm["area_error_vs_removed"]["mean"]),
                      f(gm["area_error_vs_removed"]["median"]), f(gm["area_error_vs_removed"]["p90"])],
                     ["Hausdorff (µm)", f(gm["hausdorff_um"]["mean"], 3),
                      f(gm["hausdorff_um"]["median"], 3), f(gm["hausdorff_um"]["p90"], 3)],
                     ["mean surface distance (µm)", f(gm["mean_surface_dist_um"]["mean"], 3),
                      f(gm["mean_surface_dist_um"]["median"], 3), f(gm["mean_surface_dist_um"]["p90"], 3)]],
                    ["metric", "mean", "median", "p90"]), ""]
    else:
        L += [NM, ""]

    # ---- speed
    L += ["## Clause 2 — speedup", ""]
    if speed:
        L += [f"CPU: {speed['cpu']}. GPU: {speed['gpu']}. "
              f"Load average at measurement: {', '.join(f'{x:.2f}' for x in speed['load_average_at_measurement'])}. "
              f"One 'wafer' = {speed['n_steps_per_wafer']} timesteps from initial trench to final profile. "
              "Rasterisation excluded from both sides.", ""]
        rows = []
        for k, v in speed["solver"].items():
            rows.append([f"ViennaPS, {v['threads']} thread(s)", "CPU", "—",
                         f"{v['seconds_per_wafer_median']:.3f}", "1.0×"])
        for k, v in speed["operator"].items():
            rows.append([f"operator, `{k}`", v["device"], v.get("batch", "—"),
                         f"{v['seconds_per_wafer_median']:.2e}",
                         g(speed["speedup"][k]) + "×"])
        L += [table(rows, ["configuration", "device", "batch", "s / wafer (median)",
                           "speedup vs solver 1-thread"]), ""]
        L += [f"**Like-for-like** (CPU 1 thread on both sides): "
              f"**{g(speed['speedup_like_for_like_cpu1_vs_cpu1'])}×**. "
              "The batched-H100 row is a hardware comparison as much as an algorithmic one and is "
              "reported as such.", ""]
    else:
        L += [NM, ""]

    # ---- design
    L += ["## Clause 3 — inverse design", ""]
    if design:
        s = design["summary"]
        L += [f"{s['n_targets']} targets drawn from the test split, each a profile ViennaPS "
              "actually produced from a recipe inside the training box, so a solution exists.", "",
              "All four rows are scored the same way. `true_resim` re-simulates the recipe that "
              "made the target and must be ≈0 — it is a tripwire on determinism, not a result. "
              "`surrogate_opinion` is what the operator believed its own answer achieved; the gap "
              "between it and `operator_gd` is the surrogate-reality gap.", ""]
        rows = []
        names = {"true_resim": "true recipe, re-simulated (tripwire)",
                 "operator_gd": "**gradient descent, scored in ViennaPS**",
                 "surrogate_opinion": "gradient descent, surrogate's own opinion",
                 "random_search": "random search over the operator, matched budget"}
        for k, nm in names.items():
            ae = s["area_error_vs_removed"][k]
            hd = s["hausdorff_um"][k]
            rows.append([nm, f(ae["mean"]), f(ae["median"]), f(ae["p90"]),
                         f(hd["mean"], 3)])
        L += [table(rows, ["method", "area error (mean)", "median", "p90", "Hausdorff µm (mean)"]), ""]
        L += [f"Box margin: minimum {s['box_margin']['min']:.3f} of the box width from a wall; "
              f"{s['box_margin']['n_pinned_at_wall']} of {s['n_targets']} solutions pinned against "
              "a wall (a pinned solution is a clipped answer, not an interior optimum).", ""]
    else:
        L += [NM, ""]

    # ---- what the surrogate buys, in simulator calls
    L += ["## Clause 3b — what the surrogate is worth, in simulator calls", ""]
    if invb:
        L += ["Gradient design spends **0** simulator calls searching and 1 verifying. The "
              "question that has an answer is therefore not whether 5% is good, but how many "
              "calls a search *without* the surrogate needs to reach the same shape error on "
              "the same targets. Random search over the same recipe box, every candidate "
              "evaluated in ViennaPS.", "",
              table([["targets", invb["n_targets"]],
                     ["budget (simulator calls per target)", invb["budget"]],
                     ["random search, mean final area error", f(invb["random_search_final_mean"])],
                     ["gradient design, mean area error", f(invb["gradient_mean"])],
                     ["targets where gradient was better",
                      f"{invb['n_targets_gradient_better']} / {invb['n_targets']}"],
                     ["median calls for random search to match gradient",
                      invb["calls_to_match_gradient"]["median_when_matched"]],
                     ["targets random search never matched within budget",
                      invb["calls_to_match_gradient"]["n_never_matched"]]],
                    ["quantity", "value"]), ""]
        c = invb.get("mean_best_so_far_curve") or []
        marks = [k for k in (1, 2, 4, 8, 16, 32, 48, 64, 96, 128) if k <= len(c)]
        if marks:
            L += ["Best-so-far area error against simulator calls, mean over targets — the curve "
                  "rather than one budget, so the comparison cannot hide in the budget:", "",
                  table([["random search"] + [f(c[m - 1]) for m in marks]],
                        ["simulator calls"] + [str(m) for m in marks]), ""]
    else:
        L += [NM, ""]

    # ---- generation parallelism
    if workers:
        L += ["## Appendix — generation throughput vs worker count", "",
              "Recorded because it changes the solver's seconds-per-wafer by a factor of 40 and "
              "therefore changes clause 2 if it is not controlled.", "",
              table([[w["workers"], f"{w['traj_per_s']:.3f}", f"{w['per_traj_wall_s_mean']:.1f}"]
                     for w in workers],
                    ["workers", "trajectories/s", "wall per trajectory (s)"]), ""]

    if cfg:
        L += ["## Model", "",
              table([[k, cfg.get(k)] for k in
                     ["width", "modes", "layers", "epochs", "batch", "lr",
                      "rollout_steps", "band_weight", "params", "gpu", "seed"]
                     if k in cfg], ["setting", "value"]), ""]

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
