"""Regenerate RESULTS.md from the run JSONs.

    python scripts/report.py

This is the only path by which a number enters a document in this repo. If a
figure is not in one of these JSONs it does not appear, and if a JSON is missing
the row says `[not measured]` rather than being quietly dropped -- a blank beats
a guess.
"""
from __future__ import annotations

import argparse
import datetime
import json
from pathlib import Path

NM = "[not measured]"


def read(p, default=None):
    p = Path(p)
    return json.loads(p.read_text()) if p.exists() else default


def cell(x):
    return str(x).replace("|", "\\|")


def table(rows, header):
    out = ["| " + " | ".join(cell(h) for h in header) + " |",
           "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(cell(c) for c in r) + " |")
    return "\n".join(out)


def f(x, n=4):
    return NM if x is None else f"{x:.{n}f}"


def g(x, n=1):
    return NM if x is None else f"{x:,.{n}f}"


def crossed_arm(spread):
    """Every converged run of the headline configuration that has a crossed-dt
    evaluation. The crossed number's seed spread is the whole point, so this
    reports the arm and never a single run."""
    if not spread:
        return []
    arm = []
    for r in spread.get("runs", []):
        d = Path(r["run"])
        cx = d / "test_crossed_eval.json"
        ev = d / "test_eval.json"
        if r.get("blind") or not (cx.exists() and ev.exists()):
            continue
        k = json.loads(cx.read_text())["kpi_clause_rel_l2"]
        arm.append({"run": d.name, "in_dist": r["band_rel_l2"], "crossed": k["value"],
                    "crossed_terminal": k["value_terminal_step"],
                    "beats_blind": bool(k.get("beats_recipe_blind"))})
    return sorted(arm, key=lambda a: a["run"])


def coverage_arm():
    """The crossed-split error split by whether the trajectory's per-step
    displacement is inside the training range, across every seed that has the
    analysis. One seed cannot carry this: the crossed split's seed range is
    0.227, so a coverage conclusion drawn from a single run is not a conclusion.
    """
    rows = []
    for p in sorted(Path("runs").glob("crossed_analysis*.json")):
        d = json.loads(p.read_text())
        m = d.get("displacement_matched") or {}
        if not m:
            continue
        rows.append({
            "run": Path(d.get("run", p.stem)).name,
            "in_dist": d["splits"]["test"]["band_rel_l2_mean"],
            "crossed_all": d["splits"]["test_crossed"]["band_rel_l2_mean"],
            "in_range": m["crossed_err_in_range_mean"],
            "out_range": m["crossed_err_out_of_range_mean"],
            "n_in": m["n_crossed_in_range"],
            "dt_outside": d["splits"]["test_crossed"].get("frac_dt_outside_trained_range"),
        })
    return sorted(rows, key=lambda r: r["run"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="runs/base")
    ap.add_argument("--data", default="data")
    ap.add_argument("--design", default=None,
                    help="explicit path to a design.json, if it was not "
                         "written inside the run directory")
    ap.add_argument("--design-alt", default=None,
                    help="the other protocol's design.json, reported beside the "
                         "headline one so the T-pinned/T-searched pair is visible")
    ap.add_argument("--out", default="RESULTS.md")
    a = ap.parse_args()

    run = Path(a.run)
    verify = read("runs/verify_solver.json")
    gen = read(Path(a.data) / "gen_report.json")
    cfg = read(run / "args.json", {})
    ev = read(run / "test_eval.json")
    evx = read(run / "test_crossed_eval.json")
    cf = read("runs/confound.json")
    speed = read("runs/speed.json")
    design = read(a.design) if a.design else read(run / "design.json")
    design_alt = read(a.design_alt) if a.design_alt else None
    degen = read("runs/design_degeneracy.json")
    rcurve = read("runs/random_curve.json")
    # Clause 3 replicated across seeds. Globbed rather than named, so a seed
    # that finishes after this file was last edited still counts.
    design_seeds = sorted(Path("runs").glob("design_Tfree_seed*.json"))
    design_seed_docs = [(q.name, read(q)) for q in design_seeds]
    workers = read("runs/worker_scaling.json")
    invb = read("runs/inverse_baseline.json")
    spread = read("runs/seed_spread.json")
    health = read("runs/gpu_health.json")

    L = ["# RESULTS — E4, etch-operator-twin", "",
         "Regenerated by `scripts/report.py` from run JSONs. Nothing here is typed by hand.",
         "", "> **KPI:** 2D 표면진화 rel-L2 ≤0.05 · 시뮬 대비 ≥1000× 가속 · 역설계 형상오차 ≤5%", ""]

    # ---- KPI scoreboard
    L += ["## KPI scoreboard", ""]
    rl = ev.get("kpi_clause_rel_l2") if ev else None
    sp = speed.get("kpi_clause") if speed else None
    sh = design["summary"].get("kpi_clause_shape_error") if design else None
    def _relverdict(rl):
        if not rl:
            return NM, NM
        term = rl.get("value_terminal_step")
        if term is None:
            return f(rl["value"]), ("MET" if rl["met"] else "NOT MET")
        both = rl["value"] <= 0.05 and term <= 0.05
        return (f"{rl['value']:.4f} mean / {term:.4f} final step",
                "MET" if both else ("MET (mean only)" if rl["met"] else "NOT MET"))

    _relv, _relvd = _relverdict(rl)
    rows = [
        ["rel-L2 ≤ 0.05", _relv, _relvd,
         "rollout band rel-L2, test split; both readings must pass" if rl else "—"],
        # Keyed on the like-for-like number. Keying it on the best cell of the
        # grid would award the clause to a batched H100 measured against a
        # single-threaded C++ solver.
        ["speedup ≥ 1000×",
         (g(sp["value"]) + "×") if sp else NM,
         ("MET" if sp and sp["value"] >= 1000 else "NOT MET") if sp else NM,
         (f"{sp['basis']}; throughput-vs-throughput "
          f"{g(sp.get('context_throughput_speedup'))}×, "
          f"largest cell in grid {g(sp.get('context_naive_best_cell'))}× "
          f"(`{sp.get('context_naive_configuration')}`, different hardware)") if sp else "—"],
        ["shape error ≤ 5%",
         (f(sh["value"] * 100, 2) + "%") if sh else NM,
         ("MET" if sh["met"] else "NOT MET") if sh else NM,
         "normalised area error, measured in ViennaPS" if sh else "—"],
    ]
    L += [table(rows, ["clause", "measured", "verdict", "protocol"]), ""]

    # ---- ground truth
    L += ["## Ground truth verification", ""]
    if verify:
        L += [f"ViennaPS {verify['viennaps']} / ViennaLS {verify['viennals']}, 1 OpenMP thread.", ""]
        rows = [["SDF rasteriser vs analytic plane",
                 f"{verify['sdf_exactness']['max_abs_err_um']:.2e} µm (max)",
                 f"< {verify['pass']['sdf_tol_um']} µm",
                 "PASS" if verify["pass"]["sdf_exactness"] else "FAIL"]]
        for c in verify["isotropic_recession"]:
            rows.append([f"isotropic recession, t={c['duration_min']} min",
                         f"{c['rel_err']:.2e} (rel)",
                         f"< {verify['pass']['isotropic_rel_tol']}",
                         "PASS" if c["rel_err"] < verify["pass"]["isotropic_rel_tol"] else "FAIL"])
        L += [table(rows, ["check", "measured", "tolerance", "verdict"]), ""]
        rows = [[f"Δ {p['coarse_delta']} → {p['fine_delta']}",
                 f"{p['mean_sdf_shift_um']:.4f} µm", f"{p['max_sdf_shift_um']:.4f} µm"]
                for p in verify["grid_convergence"]["pairs"]]
        L += ["**Grid convergence.** The dataset is generated at Δ = "
              f"{gen['grid_delta'] if gen else '?'}, so its own discretisation error sets a floor "
              "below which an operator error is measuring the solver's grid, not the operator.", ""]
        L += [table(rows, ["refinement", "mean surface shift (band)", "max"]), ""]
    else:
        L += [NM, ""]

    # ---- dataset
    L += ["## Dataset", ""]
    if gen:
        # .get, not [], throughout: a report that dies on one absent field tells
        # you nothing about the fields that *are* there, which defeats the point
        # of emitting [not measured] per cell.
        rows = [[s.get("split", NM), s.get("kept", NM), s.get("rejected_out_of_window", NM),
                 (f"{s['generate_wall_s']:.0f}" if "generate_wall_s" in s else NM),
                 s.get("workers", NM)] for s in gen["splits"]]
        L += [table(rows, ["split", "trajectories", "rejected (left window)",
                           "generation wall (s)", "workers"]), ""]
        L += [f"{gen['steps']} timesteps per trajectory on a {gen['grid_n']}×{gen['grid_n']} window "
              f"x ∈ {gen['window']['x']} µm, y ∈ {gen['window']['y']} µm. "
              "Timestep is chosen per recipe so every trajectory covers a comparable etch depth "
              f"({gen['target_depth_range'][0]}–{gen['target_depth_range'][1]} µm); dt is a model input.", ""]
        L += ["Recipe box (the region inverse design is confined to):", ""]
        L += [table([[k, v[0], v[1], v[2]] for k, v in
                     {**gen["recipe_box"], **gen["geom_box"]}.items()],
                    ["knob", "low", "high", "sampling"]), ""]
    else:
        L += [NM, ""]

    # ---- accuracy
    L += ["## Clause 1 — surface-evolution accuracy", ""]
    if ev:
        L += [f"Test split, {ev['n_trajectories']} trajectories × {ev['steps']} steps. "
              f"Band = |φ| < {ev['band_um']} µm around the ground-truth interface.", "",
              "Every row carries three nulls, and a number that does not beat all three is "
              "not a result.", "",
              "- **Persistence** — predict no change. An SDF over one step is mostly "
              "unchanged, so this scores far better than it deserves to.",
              "- **Recipe-blind** — advance every surface by the train-set mean per-step "
              "displacement, ignoring recipe, dt and target. This is the null that matters "
              "here: because the timestep is chosen per recipe so every trajectory covers a "
              "comparable depth, per-step displacement is nearly recipe-independent *by "
              "construction*, and a model could score well while ignoring the recipe "
              "entirely. Beating this is the evidence that the conditioning carries shape "
              "information.",
              "- **Uniform recession** — offset by the *ground truth's* mean displacement. "
              "This is an oracle: it is handed the correct amount of etch and lacks only the "
              "shape. Losing to it is not fatal; beating it is strong.", ""]
        rows = []
        for label, blk in [("one step (teacher forced)", ev["one_step"]),
                           ("full rollout", ev["rollout"])]:
            for k, name in [("op", "**operator**"), ("persist", "persistence null"),
                            ("blind", "recipe-blind null"),
                            ("uniform", "uniform-recession null (oracle)")]:
                if k not in blk:
                    continue
                rows.append([label, name, f(blk[k]["band"]["mean"]),
                             f(blk[k]["band"]["median"]), f(blk[k]["band"]["p90"]),
                             f(blk[k]["full"]["mean"])])
        L += [table(rows, ["protocol", "predictor", "band rel-L2 (mean)", "median", "p90",
                           "full-window rel-L2 (mean)"]), ""]
        L += ["Rollout band rel-L2 by step (drift compounding):", "",
              "| step | " + " | ".join(str(i + 1) for i in range(len(ev["rollout_band_rel_l2_by_step"]))) + " |",
              "|---|" + "---|" * len(ev["rollout_band_rel_l2_by_step"]),
              "| band rel-L2 | " + " | ".join(f"{v:.4f}" for v in ev["rollout_band_rel_l2_by_step"]) + " |", ""]
        gm = ev["final_profile_geometry"]
        L += ["Geometry of the final predicted profile:", "",
              table([["normalised area error", f(gm["area_error_vs_removed"]["mean"]),
                      f(gm["area_error_vs_removed"]["median"]), f(gm["area_error_vs_removed"]["p90"])],
                     ["Hausdorff (µm)", f(gm["hausdorff_um"]["mean"], 3),
                      f(gm["hausdorff_um"]["median"], 3), f(gm["hausdorff_um"]["p90"], 3)],
                     ["mean surface distance (µm)", f(gm["mean_surface_dist_um"]["mean"], 3),
                      f(gm["mean_surface_dist_um"]["median"], 3), f(gm["mean_surface_dist_um"]["p90"], 3)]],
                    ["metric", "mean", "median", "p90"]), ""]
    else:
        L += [NM, ""]

    # ---- speed
    L += ["## Clause 2 — speedup", ""]
    if speed:
        L += [f"CPU: {speed['cpu']}. GPU: {speed['gpu']}. "
              f"Load average at measurement: {', '.join(f'{x:.2f}' for x in speed['load_average_at_measurement'])}. "
              f"One 'wafer' = {speed['n_steps_per_wafer']} timesteps from initial trench to final profile. "
              "Rasterisation excluded from both sides.", ""]
        rows = []
        base_s = speed["solver"]["1_thread_single"]["seconds_per_wafer_median"]
        for k, v in speed["solver"].items():
            # the mode must be in the label: 'stepped' re-instantiates the process
            # every timestep and is ~3x slower than the single process an engineer
            # would actually run. Two rows reading 'ViennaPS, 1 thread' with a 3x
            # gap between them is how a reader ends up quoting the wrong one.
            mode = v.get("mode", "")
            lbl = f"ViennaPS, {v['threads']} thread(s)" + (f", {mode}" if mode else "")
            rows.append([lbl, "CPU", "—", f"{v['seconds_per_wafer_median']:.3f}",
                         f"{base_s / v['seconds_per_wafer_median']:.2f}×"])
        for k, v in speed["operator"].items():
            rows.append([f"operator, `{k}`", v["device"], v.get("batch", "—"),
                         f"{v['seconds_per_wafer_median']:.2e}",
                         g(speed["speedup"][k]) + "×"])
        L += [table(rows, ["configuration", "device", "batch", "s / wafer (median)",
                           "speedup vs solver 1-thread"]), ""]
        kc = speed.get("kpi_clause", {})
        if "stepped_vs_single_overhead" in kc:
            naive = (speed["solver"]["1_thread_stepped"]["seconds_per_wafer_median"]
                     / min(v["seconds_per_wafer_median"] for v in speed["operator"].values()
                           if v.get("device") == "cuda"))
            L += [f"**The denominator matters more than the model does.** Timing the solver as "
                  f"{speed['n_steps_per_wafer']} separate processes rather than one process of "
                  f"the full duration inflates it by "
                  f"**{kc['stepped_vs_single_overhead']:.2f}×**. Against that inflated "
                  f"denominator the best GPU cell would read **{naive:.0f}×** — i.e. the clause "
                  f"would have been recorded as MET, at 1000×, purely from how the reference "
                  f"was timed. Against the honest denominator the same cell reads "
                  f"**{kc['context_naive_best_cell']:.0f}×**.", ""]
        L += [f"**Like-for-like** (CPU 1 thread on both sides): "
              f"**{g(speed['speedup_like_for_like_cpu1_vs_cpu1'])}×**. "
              "The batched-H100 row is a hardware comparison as much as an algorithmic one and is "
              "reported as such.", ""]
    else:
        L += [NM, ""]

    # ---- design
    L += ["## Clause 3 — inverse design", ""]
    if design:
        s = design["summary"]
        L += [f"{s['n_targets']} targets drawn from the test split, each a profile ViennaPS "
              "actually produced from a recipe inside the training box, so a solution exists.", "",
              "All four rows are scored the same way. `true_resim` re-simulates the recipe that "
              "made the target and must be ≈0 — it is a tripwire on determinism, not a result. "
              "`surrogate_opinion` is what the operator believed its own answer achieved; the gap "
              "between it and `operator_gd` is the surrogate-reality gap.", ""]
        rows = []
        gd0 = design["targets"][0]["operator_gd_surrogate"]
        rb = design["targets"][0]["random_search"].get("budget")
        names = {"true_resim": "true recipe, re-simulated (tripwire)",
                 "operator_gd": "**gradient descent, scored in ViennaPS**",
                 "surrogate_opinion": "gradient descent, surrogate's own opinion",
                 "random_search": f"random search over the operator, {rb} candidates"}
        for k, nm in names.items():
            ae = s["area_error_vs_removed"][k]
            hd = s["hausdorff_um"][k]
            rows.append([nm, f(ae["mean"]), f(ae["median"]), f(ae["p90"]),
                         f(hd["mean"], 3)])
        L += [table(rows, ["method", "area error (mean)", "median", "p90", "Hausdorff µm (mean)"]), ""]
        L += [f"Box margin: minimum {s['box_margin']['min']:.3f} of the box width from a wall; "
              f"{s['box_margin']['n_pinned_at_wall']} of {s['n_targets']} solutions pinned against "
              "a wall (a pinned solution is a clipped answer, not an interior optimum).", ""]

        # Objection: a global area difference can hide a local defect. The reply
        # is the worst-case Hausdorff distance measured against the grid the
        # ground truth itself lives on.
        gd_h = s["hausdorff_um"]["operator_gd"]
        tr_h = s["hausdorff_um"]["true_resim"]
        if gen and gen.get("grid_delta"):
            dx = gen["grid_delta"]
            L += ["**Does the global area metric hide a local defect?** A notch or a "
                  "sidewall deviation contributes to an area difference only in proportion "
                  "to its area, so the area figure alone cannot answer this. The bound that "
                  "can is the worst-case Hausdorff distance — the largest distance from any "
                  f"point of one contour to the other — measured against the Δ = {dx} µm grid "
                  "the ground truth itself is computed on:", "",
                  table([["gradient descent's proposal", f(gd_h['mean'], 4), f(gd_h['max'], 4),
                          f"{gd_h['max']/dx:.2f}"],
                         ["true recipe re-simulated (floor)", f(tr_h['mean'], 4),
                          f(tr_h['max'], 4), f"{tr_h['max']/dx:.2f}"]],
                        ["contour", "Hausdorff µm (mean)", "worst of "
                         f"{s['n_targets']} targets", "worst, in grid cells"]), "",
                  f"The largest local deviation anywhere in the worst target is "
                  f"**{gd_h['max']/dx:.2f} of one grid cell**, against a floor of "
                  f"{tr_h['max']/dx:.2f} cells for re-simulating the true recipe. Hausdorff is "
                  "not what the clause is scored on, so this qualifies the verdict rather "
                  "than constituting it — but it is a stronger statement than the area figure "
                  "it supports.", ""]

        # Objection: the targets are a curated family. True, and it belongs here
        # rather than in a script docstring.
        L += ["**Scope, stated where it can be read.** Every target is a profile ViennaPS "
              "produced from a recipe inside the training box, with the true initial geometry "
              "supplied, at an etch depth the generator chose. That is deliberate — it "
              "guarantees a solution exists, so a failure is the optimiser's and not the "
              "target's — and it is a hard limit on what the clause certifies. **Nothing here "
              "measures inversion of an independently specified manufacturing target, a "
              "different depth regime, or a geometry outside the recipe box.** The reported "
              "shape error is a lower bound on what a novel target would cost.", ""]

        # Objection: `met` on the mean alone. Both readings, computed from the
        # per-target rows so the answer is identical across every seed's JSON
        # regardless of which version of design.py wrote it.
        ae = [r["operator_gd"]["area_error_vs_removed"] for r in design["targets"]
              if r["operator_gd"].get("area_error_vs_removed") is not None]
        trunc = sum(1 for r in design["targets"]
                    if (r["operator_gd"].get("sim_status") or {}).get("steps_ok") is False)
        if ae:
            L += [table([["mean ≤ 0.05 (literal reading of the clause)", f(sum(ae)/len(ae)),
                          "MET" if max(ae) is not None and sum(ae)/len(ae) <= 0.05 else "NOT MET"],
                         ["every target ≤ 0.05 (strict reading)", f(max(ae)),
                          "MET" if max(ae) <= 0.05 else "NOT MET"],
                         ["simulations that ran to completion",
                          f"{len(ae) - trunc}/{len(design['targets'])}",
                          "clean" if trunc == 0 else "**TRUNCATED**"]],
                        ["reading", "value", "verdict"]), "",
                  "Both readings are printed because they can disagree: a mean under 5% can "
                  "carry a target over it. The truncation row exists because "
                  "`solver.simulate()` stops at the window and repeats its last frame with "
                  "`steps_ok` False while the wrapper still reports no failure — so a zero "
                  "failure count did not, until this row, mean verification had completed.",
                  ""]

        # The two protocols, and the fact that the "optimistic" one loses.
        if design_alt:
            sa = design_alt["summary"]
            L += ["### Both protocols, and why the constrained one is worse", "",
                  "A target profile arrives with no duration attached, so whether total etch "
                  "time `T = n_steps·dt` is known is a protocol choice, not a detail. Both are "
                  "reported.", "",
                  table([[("T searched (no duration given)" if d["summary"]["dt_optimised"]
                           else "T pinned to the target's own value"),
                          f(d["summary"]["area_error_vs_removed"]["operator_gd"]["mean"]),
                          f(d["summary"]["area_error_vs_removed"]["operator_gd"]["max"]),
                          f"{d['summary']['kpi_clause_shape_error']['frac_targets_under_5pct']:.0%}",
                          f(d["summary"]["hausdorff_um"]["operator_gd"]["mean"], 3)]
                         for d in (design, design_alt)],
                        ["protocol", "area error (mean)", "max", "targets < 5%",
                         "Hausdorff µm"]), ""]
            L += ["Pinning T was labelled the *optimistic* protocol in this repo, on the "
                  "reasoning that handing over the degree of freedom that sets depth could only "
                  "help. It does not: the searched-T arm is better on both readings. Pinning T "
                  "is a **constraint**, and the constraint costs more than the information it "
                  "supplies — with T free the optimiser can trade rate against time and slide "
                  "along a family of processes that reach the same profile. The label has been "
                  "corrected wherever it appeared.", ""]

        # Shape matched is not recipe recovered. This is the claim the KPI does
        # not make, kept in its own subsection so it cannot be read as the KPI.
        if degen:
            L += ["### What is *not* claimed: the recipe is not recovered", "",
                  "The clause is 형상오차 — shape error — and shape error is what the table "
                  "above scores. The distance between the recipe the optimiser proposed and the "
                  "recipe that actually produced the target is a different quantity, and it is "
                  "large. Distances are fractions of the recipe box, log-scaled on the axes the "
                  "sampler draws in log space.", ""]
            L += [table([[("T searched" if arm["dt_optimised"] else "T pinned"),
                          f(arm["shape_error_area_vs_removed"]["mean"]),
                          f(arm["recipe_distance_unit_box"]["rms"]["mean"], 3),
                          f"{arm['recipe_distance_unit_box']['frac_beyond_10pct_of_box']:.0%}",
                          f(arm["etch_time_rel_error"]["mean"], 3),
                          f(arm["corr_recipe_distance_vs_shape_error"], 3)]
                         for arm in degen["arms"]],
                        ["protocol", "shape error", "recipe distance (RMS, fraction of box)",
                         "beyond 10% of box", "etch-time rel. error", "corr(recipe dist, shape err)"]),
                  ""]
            L += ["So the forward map is **degenerate over (rate × time)**: many processes reach "
                  "the same profile, and matching a profile does not identify the process that "
                  "made it. The correlation between the two errors is weak, which is the "
                  "mechanical statement that a small shape error does not certify a recipe. "
                  "**Anyone reading this to set a tool rather than to hit a profile would be "
                  "using a number that was not measured.**", ""]

        # H3: the random-search baseline at honest budget.
        if rcurve:
            c, comp, v = rcurve["curve"], rcurve["compute"], rcurve["verdict"]
            gdm = rcurve["gd_reference"]["mean_area_error"]
            L += ["### Clause 3b — the random-search baseline, as a curve", "",
                  f"The single random-search row above used **{rb} candidates**. Gradient "
                  f"descent used {comp['gd_restarts']} restarts × {comp['gd_iters']} iterations "
                  f"= {comp['gd_rollouts_forward']} rollouts forward *and* the same number "
                  f"backward, so at a backward costing ~{comp['backward_cost_assumed_in_forwards']:.0f} "
                  f"forwards it spent about **{comp['gd_forward_equivalents']} "
                  "forward-equivalents**. Those budgets are not comparable, and an earlier "
                  "version of `design.py`'s docstring called them comparable. The baseline is "
                  "therefore reported as an objective-versus-budget curve, and random search "
                  "keeps the target's true etch time throughout — which makes it stronger than "
                  "the searched-T method it is being compared against.", ""]
            L += [table([[b, f(c[b]["mean"]), f(c[b]["median"]), f(c[b]["max"]),
                          "**≤ GD**" if c[b]["mean"] <= gdm else ""]
                         for b in sorted(c, key=int)],
                        ["candidates", "area error (mean)", "median", "max", "vs GD"]), ""]
            L += [f"Gradient descent, same targets, same model: **{f(gdm)}**.", ""]
            if v["h3_falsified"]:
                L += [f"**H3 is falsified.** Random search reaches gradient descent's error at "
                      f"{min(v['budgets_reaching_gd'])} candidates. The hypothesis written "
                      "before the run was that it would not do so at any budget up to 16,384. "
                      "The operator is therefore demonstrated to be a usable **ranker**; the "
                      "claim that its *gradients* are what produce the answer is not supported "
                      "by this comparison.", ""]
            else:
                L += ["**H3 survives.** No budget tested reaches gradient descent's error, "
                      f"including {max(int(b) for b in c)} candidates at "
                      f"{max(int(b) for b in c) / comp['gd_forward_equivalents']:.1f}× GD's "
                      "forward-equivalent compute.", ""]
            if v.get("random_at_matched_budget") is not None:
                L += [f"At the compute-matched budget of {comp['budget_matched_to_gd']} "
                      f"candidates, random search reads "
                      f"**{f(v['random_at_matched_budget'])}** against GD's {f(gdm)}.", ""]
            cc = rcurve["cross_check"]
            L += [f"Cross-check: the N={rb} prefix is `design.py`'s own candidate set and "
                  f"reproduces its random-search mean to "
                  f"{cc.get('abs_delta', abs(cc['curve_n256_mean'] - cc['design_json_random_search_mean'])):.5f} "
                  "— not exactly, because the spectral forward pass is not bitwise "
                  "deterministic and a near-tie at the top of the ranking can flip the winner.",
                  ""]

        # Clause 3 across seeds.
        if design_seed_docs:
            vals = [(nm, d["summary"]["area_error_vs_removed"]["operator_gd"]["mean"],
                     d["summary"]["area_error_vs_removed"]["operator_gd"]["max"],
                     d["summary"]["kpi_clause_shape_error"]["frac_targets_under_5pct"])
                    for nm, d in design_seed_docs if d]
            head = ("runs/design_Tfree.json (seed1)",
                    s["area_error_vs_removed"]["operator_gd"]["mean"],
                    s["area_error_vs_removed"]["operator_gd"]["max"],
                    s["kpi_clause_shape_error"]["frac_targets_under_5pct"])
            allv = [head] + vals if design["summary"]["dt_optimised"] else vals
            means = [x[1] for x in allv]
            L += ["### Clause 3 across seeds", "",
                  "One seed is a screen, not a verdict — this repo has already withdrawn a "
                  "claim whose seed range exceeded its own mean. Same 20 targets, same "
                  "protocol (T searched), one independently trained operator each.", "",
                  table([[nm, f(m), f(mx), f"{fr:.0%}"] for nm, m, mx, fr in allv],
                        ["run", "area error (mean)", "max", "targets < 5%"]), ""]
            if len(means) >= 2:
                L += [f"Across {len(means)} seeds: mean **{f(sum(means)/len(means))}**, "
                      f"range **{f(max(means)-min(means))}**, worst seed "
                      f"**{f(max(means))}** against the 0.05 threshold. "
                      + ("Every seed meets the clause."
                         if max(means) <= 0.05 else
                         f"**{sum(1 for m in means if m > 0.05)} of {len(means)} seeds miss it.**"),
                      ""]
    else:
        L += [NM, ""]

    # ---- generalisation probe: the crossed-dt split
    L += ["## Clause 1b — the same operator when the timestep stops being adaptive", ""]
    if evx and ev:
        k, kx = ev["kpi_clause_rel_l2"], evx["kpi_clause_rel_l2"]
        L += ["The training set chooses dt per recipe so every trajectory covers a comparable "
              "etch depth. That was done to stop most of the recipe box being nearly static "
              "(which a do-nothing predictor solves), but it also compresses how much per-step "
              "displacement varies across recipes — an adversarial review caught this and the "
              "compression is measured below. The crossed split is the same recipe box with dt "
              "drawn *independently of the recipe*, so displacement varies by the rate law's "
              "own range. It is out-of-distribution by construction and is **not** the KPI "
              "number; it is the honest qualification of it.", "",
              table([["in-distribution test", f(k["value"]), f(k["value_terminal_step"]),
                      "MET" if k["met_both_readings"] else "NOT MET"],
                     ["crossed dt (OOD probe)", f(kx["value"]), f(kx["value_terminal_step"]),
                      "MET" if kx["met_both_readings"] else "NOT MET"]],
                    ["split", "rollout band rel-L2 (mean)", "terminal step", "vs ≤0.05"]), ""]
        # The crossed-dt number is NOT reportable as a single draw. Measured
        # across the converged arm its seed range is 0.2268 against an
        # in-distribution range of 0.00114 -- 200x noisier on the same pipeline.
        # A ratio computed from one seed here would be somewhere in a 4.5x band
        # and would read as a property of the protocol. So: the arm, or nothing.
        arm = crossed_arm(spread)
        if len(arm) >= 2:
            vals = [a["crossed"] for a in arm]
            ind = [a["in_dist"] for a in arm]
            rng = max(vals) - min(vals)
            L += ["Across every converged seed of the headline configuration, on the "
                  "same crossed trajectories:", "",
                  table([[a["run"], f(a["in_dist"]), f(a["crossed"]),
                          f(a["crossed_terminal"]), "yes" if a["beats_blind"] else "**no**"]
                         for a in arm]
                        + [["**mean**", f(sum(ind) / len(ind)), f(sum(vals) / len(vals)), "—",
                            f"{sum(a['beats_blind'] for a in arm)}/{len(arm)}"],
                           ["**range**", f(max(ind) - min(ind), 5), f(rng, 4), "—", "—"]],
                        ["run", "in-distribution", "crossed dt", "crossed terminal",
                         "beats recipe-blind null"]), "",
                  f"**The seed range on the crossed split ({f(rng)}) exceeds the crossed "
                  f"mean itself ({f(sum(vals) / len(vals))}), and is "
                  f"{rng / max(max(ind) - min(ind), 1e-12):,.0f}x the in-distribution "
                  f"range ({f(max(ind) - min(ind), 5)}).** The same pipeline that is "
                  "reproducible to four decimal places in distribution is not "
                  "reproducible to within a factor of 4.5 out of it. Consequently the "
                  "cost of removing the adaptive timestep is reported as a band, "
                  f"**{min(vals) / max(ind_ := sum(ind) / len(ind), 1e-12):,.0f}x to "
                  f"{max(vals) / ind_:,.0f}x**, not as a point estimate, and no "
                  "crossed-split comparison in this repo is a verdict below 8 seeds "
                  "per arm.", "",
                  f"What does not depend on the unstable magnitude: "
                  f"**{sum(a['beats_blind'] for a in arm)}/{len(arm)} seeds beat the "
                  "recipe-blind null on the crossed split**, so the operator learned "
                  "recipe-dependent dynamics rather than a protocol-shaped constant. "
                  "That conclusion is stable; the size of the protocol's help is not.", ""]
        else:
            L += [f"Crossed-dt, headline run only: **{f(kx['value'])}** mean / "
                  f"{f(kx['value_terminal_step'])} terminal — NOT MET. Only "
                  f"{len(arm)} seed(s) have a crossed evaluation, and this quantity's "
                  "seed spread is large, so this is one draw and not a value.", ""]
        if cf:
            splits = cf["splits"]
            items = splits.items() if isinstance(splits, dict) else \
                [(sp.get("split"), sp) for sp in splits]
            rows, disp = [], {}
            for name, sp in items:
                # schema moved: per_trajectory_mean_displacement -> per_trajectory_mean
                t = sp.get("per_trajectory_mean") or sp.get("per_trajectory_mean_displacement")
                ps = sp.get("per_step", {})
                disp[name] = ps.get("max_over_min")
                row = [name, sp.get("n_trajectories"), f(t.get("mean")), f(t.get("cv")),
                       f(t.get("max_over_min"), 1), f(ps.get("max_over_min"), 1)]
                for key in ("r2_displacement_on_full_conditioning",
                            "r2_displacement_on_recipe_without_dt"):
                    if key in sp:
                        row.append(f(sp[key]))
                rows.append(row)
            hdr = ["split", "n", "mean displacement µm/step", "CV", "max/min (per traj)",
                   "max/min (per step)"]
            if len(rows) and len(rows[0]) > len(hdr):
                hdr += ["R² on recipe+dt", "R² on recipe alone"]
            L += ["How much the adaptive timestep actually flattened the problem "
                  "(`runs/confound.json`):", "", table(rows, hdr), ""]
            if disp.get("test") and disp.get("crossed"):
                L += [f"Per-step displacement spans **{disp['test']:.1f}×** across the "
                      f"adaptive test split against **{disp['crossed']:.1f}×** across the "
                      f"crossed one, so the protocol compressed the rate law's range by "
                      f"about **{disp['crossed'] / disp['test']:.1f}×**. It did not remove "
                      f"it: displacement still varies by {disp['test']:.1f}× in "
                      "distribution, which is why the recipe-blind null is beaten rather "
                      "than tied.", ""]
            ov = cf.get("overlap")
            if ov:
                L += [f"Only **{ov['fraction_inside']:.1%}** of crossed trajectories "
                      f"({ov['crossed_trajectories_inside_train_range']} of "
                      f"{ov['crossed_trajectories_total']}) have a mean per-step "
                      f"displacement inside the training 1st–99th percentile "
                      f"({ov['train_p1_um']:.3f}–{ov['train_p99_um']:.3f} µm). The crossed "
                      "split is therefore mostly genuine extrapolation, not a reshuffle.", ""]
    else:
        L += [NM, ""]

    # ---- where the clause actually holds
    cvd = read("runs/coverage_verdict.json")
    if cvd:
        L += ["## Clause 1c — the failure localises to displacement coverage, "
              "but the clause still does not hold there", ""]
        L += ["The crossed split decouples dt from the recipe. Splitting those "
              "trajectories by whether their per-step displacement falls inside the range "
              "the training data covers separates two explanations the aggregate confounds: "
              "*the model cannot handle a decoupled timestep* versus *the model cannot handle "
              "displacements it never saw*. Three coverage rules are computed rather than one, "
              "because an earlier version of this section used one rule in its table and "
              "described a different one in its prose.", "",
              f"Errors are bootstrapped over trajectories ({cvd['rules']['A_test_minmax']['mean_over_steps']['in_range']['n_boot']:,} "
              "resamples, paired across seeds — the seeds share trajectories, so a resample "
              "draws trajectories, not seeds). A clause is **MET only if the upper 95% bound "
              "is under target on BOTH readings**, mean-over-steps and terminal-step, which is "
              "the rule clause 1 uses everywhere else in this repo.", ""]
        rows = []
        for name, e in cvd["rules"].items():
            for reading in ("mean_over_steps", "terminal_step"):
                ci, co = e[reading]["in_range"], e[reading]["out_of_range"]
                rows.append([f"`{name}`", f"{e['n_in']}/{cvd['n_crossed']}",
                             reading.replace("_", "-"),
                             f"{f(ci['point'])} [{f(ci['lo'])}, {f(ci['hi'])}]",
                             f(ci["worst_seed_point"]),
                             "yes" if e[reading]["met_upper_ci"] else "**no**",
                             f"{f(co['point'])} [{f(co['lo'])}, {f(co['hi'])}]"])
        L += [table(rows, ["coverage rule", "n in range", "reading",
                           "in-range mean [95% CI]", "worst seed",
                           "upper CI ≤ 0.05", "out-of-range mean [95% CI]"]), ""]
        verdicts = {n: e["verdict_in_coverage"] for n, e in cvd["rules"].items()}
        allnot = all(v == "NOT MET" for v in verdicts.values())
        L += [f"**Verdict in coverage: "
              f"{'NOT MET under every rule' if allnot else ', '.join(f'{n} {v}' for n, v in verdicts.items())}.** "
              "The mean-over-steps reading passes on its point estimate under all three rules "
              "and passes on its upper bound under the strictest one — but the **terminal-step "
              "reading fails under every rule**, and clause 1 requires both. An earlier version "
              "of this section reported only the mean and called the clause met in coverage; "
              "that was wrong and is corrected here.", ""]
        ap_ = cvd.get("a_priori_selector") or {}
        if ap_.get("mean_over_steps"):
            am, at = ap_["mean_over_steps"], ap_["terminal_step"]
            best_oracle = min(e["mean_over_steps"]["in_range"]["point"]
                              for e in cvd["rules"].values())
            L += ["### The coverage rule is a diagnostic, not something you can deploy", "",
                  "Every rule above selects on the displacement of the *simulated truth* — the "
                  "answer you do not have when you are deciding whether to trust a prediction. "
                  "The deployable version applies the same bounds to the displacement the model "
                  "itself predicts, which needs no oracle:", "",
                  table([["oracle selector (rule B)", f(best_oracle), "—"],
                         ["a-priori selector, model's own predicted displacement",
                          f"{f(am['point'])} [{f(am['lo'])}, {f(am['hi'])}]",
                          f"{f(at['point'])} [{f(at['lo'])}, {f(at['hi'])}]"]],
                        ["selector", "in-range mean-over-steps", "terminal-step"]), "",
                  f"The two selectors agree on **{ap_['agreement_with_oracle_selector']:.1%}** of "
                  f"trajectories, but the a-priori one gives **{f(am['point'])}** where the "
                  f"oracle gives {f(best_oracle)} — a factor of "
                  f"{am['point'] / max(best_oracle, 1e-12):.1f}. The disagreement is "
                  "concentrated exactly where it costs most: a trajectory the model gets badly "
                  "wrong also has its displacement badly wrong, so it is admitted into the "
                  "'covered' set by its own error. **The coverage rule localises the failure "
                  "but cannot be used to certify a prediction in advance**, which is the thing "
                  "a deployable surrogate would need.", ""]
        if cvd.get("limitations"):
            L += ["### What this analysis does not establish", ""] + \
                 [f"- {x}" for x in cvd["limitations"]] + [""]

    # ---- what the surrogate buys, in simulator calls
    L += ["## Clause 3b — what the surrogate is worth, in simulator calls", ""]
    if invb:
        L += ["Gradient design spends **0** simulator calls searching and 1 verifying. The "
              "question that has an answer is therefore not whether 5% is good, but how many "
              "calls a search *without* the surrogate needs to reach the same shape error on "
              "the same targets. Random search over the same recipe box, every candidate "
              "evaluated in ViennaPS.", "",
              table([["targets", invb["n_targets"]],
                     ["budget (simulator calls per target)", invb["budget"]],
                     ["random search, mean final area error", f(invb["random_search_final_mean"])],
                     ["gradient design, mean area error", f(invb["gradient_mean"])],
                     ["targets where gradient was better",
                      f"{invb['n_targets_gradient_better']} / {invb['n_targets']}"],
                     ["median calls for random search to match gradient",
                      invb["calls_to_match_gradient"]["median_when_matched"]],
                     ["targets random search never matched within budget",
                      invb["calls_to_match_gradient"]["n_never_matched"]]],
                    ["quantity", "value"]), ""]
        c = invb.get("mean_best_so_far_curve") or []
        marks = [k for k in (1, 2, 4, 8, 16, 32, 48, 64, 96, 128) if k <= len(c)]
        if marks:
            L += ["Best-so-far area error against simulator calls, mean over targets — the curve "
                  "rather than one budget, so the comparison cannot hide in the budget:", "",
                  table([["random search"] + [f(c[m - 1]) for m in marks]],
                        ["simulator calls"] + [str(m) for m in marks]), ""]
    else:
        L += [NM, ""]

    # ---- generation parallelism
    if workers:
        L += ["## Appendix — generation throughput vs worker count", "",
              "Recorded because it changes the solver's seconds-per-wafer by a factor of 40 and "
              "therefore changes clause 2 if it is not controlled.", "",
              table([[w["workers"], f"{w['traj_per_s']:.3f}", f"{w['per_traj_wall_s_mean']:.1f}"]
                     for w in workers],
                    ["workers", "trajectories/s", "wall per trajectory (s)"]), ""]

    if cfg:
        L += ["## Model", "",
              table([[k, cfg.get(k)] for k in
                     ["width", "modes", "layers", "epochs", "batch", "lr",
                      "rollout_steps", "band_weight", "params", "gpu", "seed"]
                     if k in cfg], ["setting", "value"]), ""]

    # ---- provenance
    #
    # A blank KPI cell has two very different causes and they looked identical
    # for three turns: the measurement is genuinely impossible ([not measured]),
    # or the script that produces it crashed and nobody noticed ([NOT RUN]).
    # Clause 3 read [not measured] from turn 4 to turn 7 because design.py was
    # being invoked against a run directory that had been renamed -- a path bug
    # wearing the costume of an honest blank. This table makes the difference
    # visible: every input the report expects, whether it was found, and when.
    expected = [
        ("clause 1 — accuracy", run / "test_eval.json", ev),
        ("clause 1b — crossed dt", run / "test_crossed_eval.json", evx),
        ("clause 2 — speed", Path("runs/speed.json"), speed),
        ("clause 3 — inverse design", Path(a.design or (run / "design.json")), design),
        ("clause 3b — simulator-call baseline", Path("runs/inverse_baseline.json"), invb),
        ("clause 3b — random-search budget curve", Path("runs/random_curve.json"), rcurve),
        ("clause 3c — recipe recovery (degeneracy)", Path("runs/design_degeneracy.json"), degen),
        ("solver verification", Path("runs/verify_solver.json"), verify),
        ("dataset", Path(a.data) / "gen_report.json", gen),
        ("adaptive-dt confound", Path("runs/confound.json"), cf),
        ("seed spread", Path("runs/seed_spread.json"), spread),
        ("GPU lease health", Path("runs/gpu_health.json"), health),
    ]
    rows = []
    for name, path, obj in expected:
        if obj is not None:
            st = datetime.datetime.utcfromtimestamp(path.stat().st_mtime)
            rows.append([name, f"`{path}`", "found", st.strftime("%Y-%m-%d %H:%M UTC")])
        else:
            rows.append([name, f"`{path}`", "**NOT RUN — file absent**", "—"])
    L += ["## Provenance — every input this report expects", "",
          "`[not measured]` above means the JSON in this table is absent. If a row says "
          "**NOT RUN**, the corresponding KPI cell is blank because a script did not "
          "produce its output, *not* because the quantity is unmeasurable.", "",
          table(rows, ["what", "file", "state", "written"]), ""]
    if spread:
        v = spread.get("verdict", {})
        L += ["### Noise floor", "",
              f"Largest within-configuration range across seeds: "
              f"**{f(v.get('largest_within_config_range'), 5)}** "
              f"({v.get('max_seeds_in_any_config')} seeds in the largest arm). "
              f"An effect smaller than this is not an effect.", ""]
        if spread.get("excluded_incomplete"):
            L += ["Runs excluded as unfinished (scoring a mid-training checkpoint "
                  "beside converged ones reads as a seed outlier):", "",
                  table([[f"`{r['run']}`", r.get("reason", "?"),
                          r.get("epochs_requested")] for r in spread["excluded_incomplete"]],
                        ["run", "why excluded", "epochs requested"]), ""]
    if health:
        L += ["### Hardware the timings were taken on", "",
              table([[pr["device"], f"{pr['median_tflops']:.1f}",
                      f"{pr['spread_pct']:.1f}%"] for pr in health["probes"]],
                    ["device", "median bf16 TFLOP/s", "run-to-run spread"]), ""]

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
