"""Regenerate WEEKEND.md from run JSONs.

    python scripts/weekend.py

WEEKEND.md is the file a tired person reads on Monday, so it must be short and it
must be current. It is generated rather than hand-written for two reasons: no
number in it can then drift from the JSON that produced it, and concurrent turns
of this loop cannot half-overwrite each other's prose -- whoever runs this last
gets a correct file.

Prose lives here. Numbers live in the JSONs. `[not measured]` is emitted for
anything no run has produced.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

NM = "`[not measured]`"


def read(p, default=None):
    try:
        return json.loads(Path(p).read_text())
    except (OSError, json.JSONDecodeError):
        return default


def f(x, n=4):
    return f"{x:.{n}f}" if isinstance(x, (int, float)) else NM


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="runs/t4_base_s0")
    ap.add_argument("--out", default="WEEKEND.md")
    a = ap.parse_args()
    run = Path(a.run)

    ev = read(run / "test_eval.json")
    evx = read(run / "test_crossed_eval.json")
    sp = read("runs/speed.json")
    dsn = read(run / "design.json") or read("runs/design.json")
    ver = read("runs/verify_solver.json", {})
    cf = read("runs/confound.json")
    gen = read("data/gen_report.json", {})
    genx = read("data/gen_report_crossed.json", {})

    k = (ev or {}).get("kpi_clause_rel_l2", {})
    kx = (evx or {}).get("kpi_clause_rel_l2", {})
    ks = (sp or {}).get("kpi_clause", {})
    kd = ((dsn or {}).get("summary") or {}).get("kpi_clause_shape_error", {})

    L = [f"# WEEKEND — E4, Etch Neural Operator Twin",
         "",
         f"*Generated by `scripts/weekend.py` at "
         f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
         "Numbers come from run JSONs; prose lives in the script. Long form is "
         "`critique_log.md` and `paper_draft.md`; `RESULTS.md` is the full table.*",
         "",
         "> **KPI:** 2D 표면진화 rel-L2 ≤0.05 · 시뮬 대비 ≥1000× 가속 · 역설계 형상오차 ≤5%",
         "",
         "## Headline: Friday vs now",
         "",
         "| clause | Friday | now |",
         "|---|---|---|",
         f"| rel-L2 ≤ 0.05 | repo did not exist | **{f(k.get('value'))}** in-distribution "
         f"({'MET' if k.get('met') else 'NOT MET' if k else NM}); "
         f"**{f(kx.get('value'))}** on the crossed-dt probe "
         f"({'MET' if kx.get('met') else 'NOT MET' if kx else NM}) |",
         f"| ≥1000× speedup | repo did not exist | "
         f"**{f(ks.get('value'), 1) + '×' if ks else NM}** like-for-like "
         f"({'MET' if ks.get('met') else 'NOT MET' if ks else NM}) |",
         f"| shape error ≤ 5% | repo did not exist | "
         f"**{f(kd.get('value')) if kd else NM}** "
         f"({'MET' if kd.get('met') else 'NOT MET' if kd else NM}) |",
         ""]

    if k and kx:
        L += ["## The one paragraph that matters", "",
              f"The operator meets the accuracy clause with room to spare — "
              f"**{f(k['value'])}** against ≤0.05, rollout band rel-L2 over "
              f"{ev['n_trajectories']} held-out trajectories — and beats every null by two "
              f"orders of magnitude (persistence {f(k['persistence_null'], 3)}, recipe-blind "
              f"{f(k['recipe_blind_null'], 3)}, oracle uniform-recession "
              f"{f(k['uniform_recession_null'], 3)}). **But** the training protocol picks the "
              f"timestep per recipe so every trajectory covers a similar etch depth, which "
              f"compresses the rate law's spread. On a crossed split where the timestep is "
              f"drawn independently of the recipe, the same model gives **{f(kx['value'])}** — "
              f"a factor of {kx['value']/k['value']:.1f} worse, and a miss. Both are real, both "
              f"are in `RESULTS.md`, and clause 1 should not be quoted without the second.", "",
              f"The operator is still doing real work: on the crossed split it beats the "
              f"recipe-blind null by {kx['recipe_blind_null']/kx['value']:.1f}×, so it learned the "
              f"rate law, not a constant advance.", ""]

    # `runs/confound.json` is written by two different scripts in this repo with
    # two different shapes; take the one we understand and fall through otherwise
    # rather than aborting the whole file for one optional paragraph.
    cf_splits = (cf or {}).get("splits") or []
    if cf and all(isinstance(x, dict) for x in cf_splits) and cf_splits:
        rows = {s["split"]: s for s in cf_splits}
        t, c = rows.get("test"), rows.get("test_crossed")
        if t and c:
            L += [f"Displacement spread across recipes: **"
                  f"{t['per_trajectory_mean_displacement']['max_over_min']:.1f}×** on the "
                  f"adaptive test split against **"
                  f"{c['per_trajectory_mean_displacement']['max_over_min']:.1f}×** on the "
                  f"crossed one — the protocol compressed the physics by about "
                  f"{c['per_trajectory_mean_displacement']['max_over_min']/t['per_trajectory_mean_displacement']['max_over_min']:.1f}×.", ""]

    gc = (ver.get("grid_convergence") or {}).get("pairs") or []
    if gc and ev:
        msd = ev["final_profile_geometry"]["mean_surface_dist_um"]["mean"]
        L += ["## A ceiling that is already binding", "",
              f"Operator mean surface distance to ground truth is **{msd:.4f} µm**. The "
              f"solver's own grid error between Δ={gc[-1]['coarse_delta']} (what the dataset "
              f"uses) and Δ={gc[-1]['fine_delta']} is **{gc[-1]['mean_sdf_shift_um']:.4f} µm**. "
              "The operator is already closer to its training target than that target is to a "
              "converged solution, so further in-distribution accuracy work fits the "
              "discretisation, not the physics. That is why the next experiment is the "
              "crossed split, not a bigger model.", ""]

    L += ["## What was tried that did not work, and what it rules out", "",
          "1. **90-way parallel dataset generation.** Throughput *peaks at 8 workers and "
          "falls at 90* (`runs/worker_scaling.json`) — ViennaPS's flux solver is a "
          "bandwidth-bound Monte Carlo ray trace. Rules out treating a 192-core box as free "
          "parallelism, and matters for clause 2 because solver wall-clock then varies ~40× "
          "with machine load.",
          "2. **A single global timestep.** The etch rate spans ~20× across the recipe box, so "
          "one dt leaves most of the box nearly static — which a do-nothing predictor solves. "
          "Rules out the naive fixed-dt dataset.",
          "3. **The per-recipe timestep that fixed (2).** It compressed the rate law's spread; "
          "an adversarial review caught it and measurement put the cost at the factor quoted "
          "above. Rules out quoting the in-distribution number alone.",
          "4. **Hypothesis H1** — that the 10-step rollout would miss ≤0.05 through compounding "
          "drift. Falsified. Drift is real and monotonic but starts too low to matter over "
          "this horizon. Recorded as falsified rather than reframed.",
          "5. **Running ViennaPS in the same process as CUDA work.** One `simulate()` call "
          "permanently breaks cuFFT (`CUFFT_EXEC_FAILED` on every later backward). Rules out a "
          "single-process design loop; simulation now runs in a spawn subprocess pool.",
          "6. **An unguarded `simulate()`.** Fine under adaptive dt, but inverse design "
          "proposes arbitrary recipes and one verification run sat >13 min before being "
          "killed. Now stops at the window with `steps_ok` False.",
          ""]

    L += ["## Decisions that need a human", "",
          "**D1 — which speedup number goes on the board.** The grid contains a batched-H100-"
          "vs-1-thread-CPU figure and a like-for-like CPU-1-thread figure. The catalog says "
          "\"시뮬 대비 ≥1000× 가속\" without naming hardware.",
          "- *Option A (taken by default in code):* the like-for-like figure is the KPI number, "
          "and the clause reads `UNREACHABLE` if it falls short, with the grid as evidence.",
          "- *Option B:* the batched-GPU figure is the KPI number. Defensible only if the "
          "deployment story is explicitly batched inference on an H100.",
          "",
          "**D2 — whether the crossed-dt split is a probe or a training target.**",
          "- *Option A (recommended):* keep the training set, report the crossed split as a "
          "generalisation probe. Cheap, and the honest negative is a real finding.",
          "- *Option B:* retrain on a mixture of adaptive and independent dt. Probably the "
          "better model, but it changes the protocol mid-flight, so before/after numbers are "
          "not comparable and both must be reported.",
          "",
          "**D3 — whether ≤5% shape error is judged on the mean or the tail.** A mean under 5% "
          "can hide corner-case failures. `design.py` reports mean, median, p90, max and the "
          "fraction of targets under 5%; the KPI cell currently uses the mean, which is the "
          "literal reading of the clause.",
          ""]

    L += ["## Still running, and how to check it", "",
          "```bash",
          "cd ~/Documents/workspace/etch-operator-twin",
          "python scripts/report.py --run " + str(run) + "   # regenerate RESULTS.md",
          "python scripts/weekend.py --run " + str(run) + "  # regenerate this file",
          "for t in tests/test_*.py; do python $t; done      # 25 tests",
          "ls runs/                                          # one dir per run",
          "```", ""]
    if gen.get("splits"):
        tot = sum(s["kept"] for s in gen["splits"])
        L += [f"Dataset: {tot} adaptive-dt trajectories "
              f"({', '.join(str(s['kept']) + ' ' + s['split'] for s in gen['splits'])}), "
              f"{gen['steps']} steps on a {gen['grid_n']}² window."]
    if genx.get("splits"):
        s0 = genx["splits"][0]
        L += [f"Crossed-dt probe: {s0['kept']} kept, {s0['rejected_out_of_window']} rejected for "
              "leaving the window — so that split is biased against fast recipes at long dt "
              "and its number is if anything optimistic."]
    L += [""]

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
